export const metadata = {
  imagePath: "agent-input/feature-carousel/winwinkit.jpg",
  name: "use-cases-flow",
  keywords: [
    "use cases",
    "referral",
    "referral program",
    "rewards",
    "flow chart",
    "diagram",
    "user flow",
    "feature cards",
    "dark theme",
    "neon",
    "lime green",
    "winwinkit",
    "basic",
    "credit",
    "offer codes",
    "app icon",
    "new user",
    "referring user",
    "invitation",
    "invite flow",
    "reward system",
    "affiliate",
    "coming soon badge",
  ],
  fontFamily: ["Inter"],
};
