export const metadata = {
  imagePath: "agent-input/feature-carousel/order.jpg",
  name: "canvas-view-showcase",
  keywords: [
    "canvas view",
    "customize view",
    "note-taking",
    "thought organization",
    "visual workspace",
    "freeform canvas",
    "list view",
    "gallery view",
    "view switcher",
    "tabs",
    "productivity",
    "knowledge management",
    "notes app",
    "dark theme",
    "app preview",
    "feature showcase",
    "urban design",
    "architecture",
    "workspace",
    "saas",
    "landing page",
    "flexible views",
    "drag and drop",
    "idea collection",
  ],
  fontFamily: ["Inter"],
};
