export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-27.jpg",
  name: "landingfolio-hero-27",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "SaaS",
    "dark theme",
    "dark mode",
    "ClarityUI",
    "team collaboration",
    "video preview",
    "play video",
    "CTA",
    "call to action",
    "free trial",
    "navigation",
    "header",
    "startup",
    "marketing",
    "conversion",
    "landingfolio",
    "business",
    "professional website",
    "blocks",
    "components",
    "UI kit",
    "navy background",
    "blue accent",
    "italic headline",
    "centered layout",
    "team photo",
    "rounded card",
    "video button",
  ],
  fontFamily: ["Inter"],
};
