export const metadata = {
  imagePath: "agent-input/lead-capture-hero/lance.jpg",
  name: "lance-hero",
  keywords: [
    "hero",
    "lead capture",
    "email capture",
    "freelance",
    "banking",
    "fintech",
    "finance",
    "landing page",
    "signup form",
    "CTA",
    "call to action",
    "dark theme",
    "dashboard preview",
    "flow diagram",
    "money flow",
    "account management",
    "savings",
    "paycheck",
    "taxes",
    "italic headline",
    "serif font",
    "centered layout",
  ],
  fontFamily: ["Playfair Display", "Inter"],
};
