export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-19.jpg",
  name: "landingfolio-hero-19",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "NFT",
    "NFT marketplace",
    "digital art",
    "artwork",
    "crypto",
    "ethereum",
    "ETH",
    "blockchain",
    "collectibles",
    "pixel art",
    "8-bit",
    "retro",
    "bid",
    "auction",
    "marketplace",
    "artist",
    "gallery",
    "cards",
    "carousel",
    "navigation",
    "header",
    "cart",
    "shopping cart",
    "stats",
    "statistics",
    "light theme",
    "clean design",
    "minimal",
    "modern",
    "rareblocks",
    "landingfolio",
    "web3",
    "decentralized",
    "reserved price",
    "explore",
    "browse",
    "collection",
  ],
  fontFamily: ["Inter"],
};
