export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-8.jpg",
  name: "landingfolio-hero-8",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "SaaS",
    "no-code",
    "UI kit",
    "dark theme",
    "dark background",
    "navigation bar",
    "call to action",
    "CTA",
    "primary button",
    "secondary button",
    "3D cards",
    "floating cards",
    "perspective",
    "isometric",
    "screenshots",
    "product showcase",
    "rareblocks",
    "landingfolio",
    "split layout",
    "two column",
    "website builder",
    "template",
    "UI components",
    "landing page builder",
  ],
  fontFamily: ["Inter"],
};
