export const metadata = {
  imagePath: "agent-input/how-it-works/2.png",
  name: "how-it-works-steps",
  keywords: [
    "how it works",
    "steps",
    "process",
    "workflow",
    "onboarding",
    "subscribe",
    "request",
    "receive",
    "pricing",
    "cards",
    "features",
    "1 2 3",
    "simple steps",
    "getting started",
    "three steps",
    "service flow",
    "customer journey",
    "signup flow",
  ],
  fontFamily: ["Playfair Display", "Inter"],
};
