export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-10.jpg",
  name: "landingfolio-hero-10",
  keywords: [
    "hero section",
    "landing page",
    "collaboration",
    "remote work",
    "saas",
    "startup",
    "team collaboration",
    "light theme",
    "mint green",
    "orange accent",
    "CTA button",
    "watch video",
    "navigation bar",
    "header",
    "illustration",
    "UI mockup",
    "profile cards",
    "chat bubble",
    "design tool",
    "postcrafts",
    "remote collaboration",
    "two column layout",
    "highlighted text",
    "underline effect",
  ],
  fontFamily: ["Inter"],
};
