export const metadata = {
  imagePath: "agent-input/contact-form/8px-studio.jpg",
  name: "8px-studio",
  keywords: [
    "contact form",
    "contact us",
    "contact section",
    "form",
    "two column layout",
    "split layout",
    "minimal form",
    "clean design",
    "minimalist",
    "light theme",
    "white background",
    "submit form",
    "email form",
    "message form",
    "inquiry form",
    "business contact",
    "services link",
    "underline input",
    "border-bottom input",
    "8px studio",
  ],
  fontFamily: ["Inter"],
};
