export const metadata = {
  imagePath: "agent-input/lead-capture-hero/arkive.jpg",
  name: "arkive-hero",
  keywords: [
    "hero",
    "lead capture",
    "email capture",
    "waitlist",
    "landing page",
    "document scanner",
    "document management",
    "dark theme",
    "teal background",
    "green accent",
    "startup",
    "saas",
    "early access",
    "app preview",
    "cta",
    "call to action",
    "email form",
    "badge",
    "pill badge",
    "modern",
    "minimal",
    "arkive",
    "scan documents",
    "upload documents",
  ],
  fontFamily: ["Inter"],
};
