export const metadata = {
  imagePath: "agent-input/testimonial-slider/move-to-be-more.jpg",
  name: "move-to-be-more",
  keywords: [
    "testimonial",
    "testimonials",
    "slider",
    "carousel",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "quotes",
    "coaching",
    "life coach",
    "personal development",
    "self improvement",
    "potential",
    "cream background",
    "beige theme",
    "warm colors",
    "light theme",
    "three column",
    "grid layout",
    "italic headline",
    "serif font",
    "playfair display",
    "profile cards",
    "avatar",
    "author info",
    "pagination dots",
    "navigation arrows",
    "landing page",
    "professional services",
    "consultant",
    "chiropractor",
    "HR manager",
    "executive",
  ],
  fontFamily: ["Playfair Display", "Inter"],
};
