export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-7.jpg",
  name: "landingfolio-hero-7",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "dark theme",
    "dark mode",
    "design inspiration",
    "designers",
    "developers",
    "marketers",
    "creative",
    "3D graphics",
    "abstract shapes",
    "torus",
    "gradient",
    "navigation",
    "header",
    "CTA",
    "call to action",
    "button",
    "SaaS",
    "startup",
    "UI kit",
    "DuskUI",
    "design hub",
    "unlimited",
    "inspiration",
    "modern",
    "futuristic",
    "purple accent",
    "italic headline",
    "serif italic",
    "statistics",
    "trend",
  ],
  fontFamily: ["Inter"],
};
