export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-14.jpg",
  name: "landingfolio-hero-14",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "e-commerce",
    "ecommerce",
    "fitness",
    "fitness equipment",
    "sports",
    "activewear",
    "athletic",
    "workout",
    "gym",
    "health",
    "wellness",
    "product showcase",
    "product cards",
    "floating cards",
    "shopping",
    "retail",
    "coupon",
    "discount",
    "promo",
    "promotion",
    "CTA",
    "call to action",
    "navigation",
    "header",
    "category menu",
    "cart",
    "shopping cart",
    "search",
    "login",
    "account",
    "smartwatch",
    "running shoes",
    "lifestyle",
    "clean design",
    "minimal",
    "light theme",
    "white background",
    "rareblocks",
    "landingfolio",
    "serif font",
    "elegant",
  ],
  fontFamily: ["Inter"],
};
