export const metadata = {
  imagePath: "agent-input/biography/nodejs-cli.jpg",
  name: "nodejs-cli",
  keywords: [
    "biography",
    "bio",
    "profile",
    "personal",
    "about me",
    "portfolio",
    "developer",
    "open source",
    "github",
    "nodejs",
    "javascript",
    "cli",
    "command line",
    "tedx",
    "speaker",
    "wordpress",
    "google developer",
    "devrel",
    "award winning",
    "github star",
    "light theme",
    "warm background",
    "brush stroke",
    "watercolor",
    "artistic",
    "creative",
    "personal website",
    "landing page",
    "introduction",
    "professional",
    "tech",
    "engineer",
    "software developer",
    "green accent",
    "serif heading",
    "italic text",
    "underline links",
    "decorative dots",
    "profile image",
    "circular photo",
    "ahmad awais",
    "opensource",
    "maintainer",
    "contributor",
  ],
  fontFamily: ["Playfair Display", "Inter"],
};
