export const metadata = {
  imagePath: "agent-input/testimonial-slider/melbourne-web-studio.jpg",
  name: "melbourne-web-studio-testimonial",
  keywords: [
    "testimonial",
    "testimonials",
    "slider",
    "carousel",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "quotes",
    "quote card",
    "google rating",
    "google reviews",
    "5 star rating",
    "star rating",
    "dark theme",
    "dark background",
    "slate background",
    "two column",
    "split layout",
    "italic headline",
    "cursive font",
    "script font",
    "happy customers",
    "client testimonials",
    "navigation arrows",
    "up down navigation",
    "vertical navigation",
    "gold accent",
    "amber accent",
    "google logo",
    "author info",
    "avatar",
    "badge",
    "pill badge",
    "landing page",
    "saas",
    "startup",
    "agency",
    "web studio",
    "web design",
    "ecommerce",
    "business",
  ],
  fontFamily: ["Pacifico", "Inter"],
};
