export const metadata = {
  imagePath: "agent-input/contact-form/shift.jpg",
  name: "shift-contact-form",
  keywords: [
    "contact form",
    "contact us",
    "inquiry form",
    "lead capture",
    "marketplace",
    "brand strategy",
    "experts",
    "consultation",
    "SHIFT",
    "light theme",
    "gray background",
    "pill input",
    "rounded input",
    "centered layout",
    "minimal form",
    "clean design",
    "professional contact",
    "business inquiry",
    "B2B contact",
    "speak with experts",
    "marketplace strategy",
    "brand consultation",
    "simple form",
    "purple accent",
    "dark purple button",
    "elegant form",
    "enterprise contact",
    "two column inputs",
    "grid layout",
  ],
  fontFamily: ["Inter"],
};
