export const metadata = {
  imagePath: "agent-input/biography/60-tips-logo-design.jpg",
  name: "sixty-tips-logo-design",
  keywords: [
    "biography",
    "author bio",
    "about section",
    "profile",
    "designer profile",
    "logo designer",
    "brand design",
    "specialist",
    "book introduction",
    "author introduction",
    "centered layout",
    "avatar",
    "profile image",
    "heart icon",
    "dotted heart",
    "minimal design",
    "clean layout",
    "light theme",
    "gray background",
    "about me",
    "personal branding",
    "gal shir",
    "60 tips",
    "logo design book",
    "ebook landing",
    "course landing",
    "testimonial",
    "founder bio",
    "creator bio",
  ],
  fontFamily: ["Inter"],
};
