export const metadata = {
  imagePath: "agent-input/contact-form/incab-franchise.jpg",
  name: "incab-franchise",
  keywords: [
    "contact form",
    "franchise form",
    "franchise ownership",
    "lead capture",
    "business inquiry",
    "minimal form",
    "clean form",
    "light theme",
    "white background",
    "single column form",
    "simple contact form",
    "get started form",
    "franchise inquiry",
    "business contact",
    "enterprise form",
    "B2B contact",
    "lead generation",
    "thin typography",
    "light font weight",
    "elegant headline",
    "privacy policy",
    "terms and conditions",
    "pill button",
    "rounded button",
    "arrow icon button",
    "minimal design",
    "clean layout",
    "professional form",
    "corporate contact",
    "incab",
  ],
  fontFamily: ["Inter"],
};
