export const metadata = {
  imagePath: "agent-input/testimonial-tweets/ai-profile-picture-generator.jpg",
  name: "ai-profile-picture-generator",
  keywords: [
    "testimonial",
    "testimonials",
    "twitter",
    "tweets",
    "social proof",
    "masonry layout",
    "bento grid",
    "AI",
    "profile picture",
    "avatar generator",
    "customer reviews",
    "social media",
    "gradient text",
    "statistics",
    "counter",
    "happy customers",
    "light theme",
    "white background",
    "profilepicture.ai",
    "multi-column",
    "irregular grid",
    "tweet cards",
    "user testimonials",
    "product testimonial",
    "SaaS testimonial",
    "AI generated",
    "profile photos",
    "danny postma",
  ],
  fontFamily: ["Inter"],
};
