export const metadata = {
  imagePath: "agent-input/before-after/vidflow.jpg",
  name: "vidflow-before-after",
  keywords: [
    "before after",
    "before and after",
    "comparison",
    "video player",
    "video editor",
    "video platform",
    "youtube style",
    "video ui",
    "media player",
    "video thumbnail",
    "cream background",
    "light theme",
    "warm palette",
    "olive green",
    "minimal design",
    "clean ui",
    "cta button",
    "start now",
    "video title",
    "watch later",
    "share button",
    "playback controls",
    "video controls",
    "timeline",
    "progress bar",
    "landing page",
    "product showcase",
    "saas",
    "video service",
    "streaming",
    "content platform",
  ],
  fontFamily: ["DM Serif Display", "Inter"],
};
