export const metadata = {
  imagePath: "agent-input/biography/riveted-podcast.jpg",
  name: "riveted-podcast",
  keywords: [
    "biography",
    "podcast",
    "host",
    "hosts",
    "hosted by",
    "profile",
    "profiles",
    "team",
    "team members",
    "about us",
    "journalist",
    "writer",
    "editor",
    "author",
    "two column",
    "three column",
    "grid layout",
    "white background",
    "light theme",
    "clean design",
    "minimal",
    "minimalist",
    "professional",
    "portrait",
    "headshot",
    "photo",
    "avatar",
    "bio",
    "biography card",
    "person card",
    "staff",
    "crew",
    "contributors",
    "italic text",
    "publication names",
    "magazine",
    "media",
    "journalism",
    "creative",
    "editorial",
    "content creator",
    "influencer",
    "expert",
    "speaker",
    "Amy Wallace",
    "Mary Melton",
    "riveted",
  ],
  fontFamily: ["Inter"],
};
