export const metadata = {
  imagePath: "agent-input/dribble-hero/supermi.png",
  name: "supermi-hero",
  keywords: [
    "hero",
    "messaging",
    "dashboard",
    "chat",
    "communication",
    "SaaS",
    "landing page",
    "CTA",
    "call to action",
    "light theme",
    "gradient background",
    "product preview",
    "messaging app",
    "team collaboration",
    "channel management",
    "conversational",
    "next-gen",
    "pink gradient",
    "peach gradient",
    "centered layout",
    "navigation",
    "login button",
    "serif headline",
    "dashboard preview",
    "chat interface",
  ],
  fontFamily: ["DM Serif Display", "Inter"],
};
