export const metadata = {
  imagePath: "agent-input/beautiful-sections/rysa-hero.png",
  name: "rysa-hero",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "fashion",
    "wardrobe",
    "styling",
    "style app",
    "premium",
    "luxury",
    "minimalist",
    "clean design",
    "white background",
    "early access",
    "waitlist",
    "CTA",
    "call to action",
    "serif font",
    "italic headline",
    "ASCII art",
    "halftone illustration",
    "fashion illustration",
    "two column layout",
    "mobile app",
    "decision makers",
    "productivity",
    "efficiency",
    "personal styling",
    "wardrobe management",
    "digital wardrobe",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
