export const metadata = {
  imagePath: "agent-input/biography/portfolio-final-final-2023.jpg",
  name: "portfolio-final-final-2023",
  keywords: [
    "biography",
    "bio",
    "about the author",
    "author bio",
    "portfolio",
    "personal",
    "about me",
    "designer",
    "product designer",
    "profile",
    "minimal",
    "minimalist",
    "light theme",
    "white background",
    "clean design",
    "simple layout",
    "two column",
    "profile image",
    "grayscale photo",
    "black and white",
    "serif title",
    "italic",
    "experience",
    "work history",
    "consulting",
    "freelance",
    "companies",
    "clients",
    "twitter",
    "amex",
    "adidas",
    "hsbc",
    "mercedes-benz",
    "blinkist",
    "ikea",
    "professional",
    "industry experience",
    "portfolio link",
    "orange accent",
    "text link",
    "author section",
    "book author",
    "course creator",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
