export const metadata = {
  imagePath: "agent-input/testimonial-slider/diego-toda-de-oliveira.jpg",
  name: "diego-testimonial-slider",
  keywords: [
    "testimonial",
    "testimonials",
    "slider",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "quotes",
    "quote card",
    "light theme",
    "light background",
    "blue-gray background",
    "white cards",
    "tilted cards",
    "rotated cards",
    "card rotation",
    "two cards",
    "side by side",
    "happy",
    "background text",
    "large text background",
    "watermark text",
    "diego",
    "freelancer",
    "designer portfolio",
    "client testimonials",
    "B2B",
    "professional",
    "clean design",
    "minimal",
    "landing page",
    "saas",
    "startup",
    "uppercase",
    "tracking wide",
    "shadow cards",
  ],
  fontFamily: ["Inter"],
};
