export const metadata = {
  imagePath: "agent-input/biography/endless-2023.jpg",
  name: "endless-2023",
  keywords: [
    "biography",
    "bio",
    "about",
    "about us",
    "about me",
    "who we are",
    "team",
    "founder",
    "designer",
    "design agency",
    "agency",
    "studio",
    "introduction",
    "personal",
    "profile",
    "portfolio",
    "landing page",
    "light theme",
    "white background",
    "minimal",
    "minimalist",
    "clean design",
    "simple layout",
    "text heavy",
    "long form",
    "article",
    "story",
    "narrative",
    "transparent",
    "honest",
    "experience",
    "expertise",
    "professional",
    "creative",
    "startup",
    "company",
    "australia",
    "western australia",
    "daryl",
    "endless",
    "profile image",
    "circular avatar",
    "round avatar",
    "float right",
    "text wrap",
    "sans-serif",
    "paragraph",
    "multi-paragraph",
    "readable",
    "trust",
    "relationship",
    "client",
    "quality",
    "craftsmanship",
    "attention to detail",
  ],
  fontFamily: ["Inter"],
};
