export const metadata = {
  imagePath: "agent-input/contact-form/blockjoy.jpg",
  name: "blockjoy-contact-form",
  keywords: [
    "contact form",
    "contact",
    "form",
    "contact us",
    "get in touch",
    "lets chat",
    "message form",
    "inquiry form",
    "feedback form",
    "support form",
    "lime green",
    "bright green",
    "neon green",
    "green background",
    "pill inputs",
    "rounded inputs",
    "minimal form",
    "clean form",
    "modern form",
    "horizontal inputs",
    "textarea",
    "dropdown select",
    "send message",
    "name input",
    "email input",
    "message input",
    "SaaS",
    "startup",
    "tech",
    "blockjoy",
  ],
  fontFamily: ["Inter"],
};
