export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-37.jpg",
  name: "landingfolio-hero-37",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "bakery",
    "bread",
    "artisan",
    "bread making",
    "food",
    "restaurant",
    "cafe",
    "cooking",
    "baking",
    "culinary",
    "course",
    "masterclass",
    "tutorial",
    "video",
    "trailer",
    "watch trailer",
    "play video",
    "dark theme",
    "black background",
    "split layout",
    "two column",
    "image left",
    "text right",
    "serif font",
    "italic",
    "elegant",
    "rustic",
    "warm",
    "organic",
    "natural",
    "CTA",
    "call to action",
    "outlined button",
    "pill button",
    "rounded button",
    "play button",
    "navigation",
    "header",
    "minimal nav",
    "BakerStreet",
    "landingfolio",
    "video hero",
    "image hero",
    "split hero",
    "sourdough",
    "wheat",
    "artisanal",
    "hands holding bread",
    "food photography",
    "knead",
    "professional",
    "online course",
    "learn baking",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
