export const metadata = {
  imagePath: "agent-input/landingfolio-stats/stats-4.jpg",
  name: "stats-4",
  keywords: [
    "stats",
    "statistics",
    "numbers",
    "metrics",
    "business stats",
    "company stats",
    "years in business",
    "team members",
    "projects delivered",
    "customer success",
    "four columns",
    "grid layout",
    "cards",
    "white cards",
    "border cards",
    "rounded cards",
    "icons",
    "magenta icon",
    "pink accent",
    "lightning icon",
    "users icon",
    "briefcase icon",
    "thumbs up icon",
    "clean design",
    "minimal",
    "modern",
    "professional",
    "corporate",
    "landing page",
    "section",
  ],
  fontFamily: ["Inter"],
};
