export const metadata = {
  imagePath: "agent-input/before-after/supertoons.jpg",
  name: "supertoons-before-after",
  keywords: [
    "before after",
    "comparison",
    "image transformation",
    "AI art",
    "Ghibli style",
    "anime style",
    "photo to cartoon",
    "photo to anime",
    "image converter",
    "style transfer",
    "AI image generation",
    "supertoons",
    "photo transformation",
    "avatar",
    "character design",
    "social proof",
    "counter",
    "statistics",
    "light theme",
    "white background",
    "slider",
    "showcase",
    "product demo",
    "feature preview",
    "image processing",
    "neural style transfer",
    "art filter",
    "portrait transformation",
  ],
  fontFamily: ["Inter"],
};
