export const metadata = {
  imagePath: "agent-input/contact-form/brewitty.jpg",
  name: "brewitty",
  keywords: [
    "contact form",
    "contact-form",
    "contact us",
    "get in touch",
    "lets chat",
    "inquiry form",
    "message form",
    "lead form",
    "lead generation",
    "coffee",
    "brewing",
    "vintage phone",
    "retro phone",
    "rotary phone",
    "telephone",
    "call us",
    "zoom meeting",
    "meeting",
    "consultation",
    "booking",
    "schedule",
    "teal background",
    "mint background",
    "light blue",
    "creative agency",
    "playful",
    "quirky",
    "fun",
    "italic title",
    "input fields",
    "name email phone",
    "message textarea",
    "CTA button",
    "refills",
    "audience",
    "single column form",
    "centered form",
    "illustration",
    "hand drawn",
    "vintage illustration",
    "brewitty",
  ],
  fontFamily: ["DM Serif Display", "Inter"],
};
