export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-22.jpg",
  name: "landingfolio-hero-22",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "finance app",
    "expense tracker",
    "expense management",
    "fintech",
    "mobile app",
    "AI",
    "artificial intelligence",
    "budget",
    "money management",
    "personal finance",
    "app store",
    "google play",
    "download app",
    "mobile first",
    "smartphone mockup",
    "hand holding phone",
    "CTA",
    "call to action",
    "mint green",
    "pastel",
    "clean design",
    "minimal",
    "modern",
    "startup",
    "B2C",
    "consumer app",
    "postcrafts",
    "landingfolio",
    "navigation",
    "header",
    "app download",
    "daily expenses",
    "spending tracker",
  ],
  fontFamily: ["Inter"],
};
