export const metadata = {
  imagePath: "agent-input/feature-carousel/helo.jpg",
  name: "email-feature-showcase",
  keywords: [
    "email",
    "testing",
    "debugging",
    "smtp",
    "debug views",
    "broken link checker",
    "spam report",
    "sharing",
    "remote mailboxes",
    "helo",
    "email client",
    "developer tools",
    "feature list",
    "feature showcase",
    "app preview",
    "macOS window",
    "gradient decoration",
    "swiss army knife",
    "saas",
    "landing page",
    "two column layout",
    "interactive tabs",
  ],
  fontFamily: ["Inter"],
};
