export const metadata = {
  imagePath: "agent-input/lead-capture-hero/designbell.jpg",
  name: "designbell-hero",
  keywords: [
    "hero section",
    "lead capture",
    "waitlist",
    "email signup",
    "landing page",
    "dark theme",
    "navy blue",
    "design agency",
    "subscription service",
    "founding member",
    "brand design",
    "unlimited designs",
    "SaaS landing",
    "startup",
    "launch page",
    "coming soon",
    "pre-launch",
    "newsletter signup",
    "email input",
    "CTA button",
    "trusted by logos",
    "social proof",
    "badge",
    "pill button",
  ],
  fontFamily: ["Inter"],
};
