export const metadata = {
  imagePath: "agent-input/dribble-hero/ping-space.png",
  name: "ping-space-hero",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "team collaboration",
    "workspace",
    "productivity",
    "SaaS",
    "chat",
    "messaging",
    "project management",
    "team communication",
    "all-in-one",
    "collaboration tool",
    "document sharing",
    "thread",
    "approval workflow",
    "remote work",
    "teamwork",
    "cloud workspace",
    "light theme",
    "sky background",
    "blue gradient",
    "app screenshot",
    "product mockup",
    "browser mockup",
    "CTA buttons",
    "call to action",
    "get started",
    "live demo",
    "navigation bar",
    "floating labels",
    "dreamy",
    "airy",
    "clean design",
    "modern",
    "startup",
  ],
  fontFamily: ["Inter"],
};
