export const metadata = {
  imagePath: "agent-input/testimonial-slider/wegems.jpg",
  name: "wegems-testimonial-slider",
  keywords: [
    "testimonial",
    "testimonials",
    "slider",
    "carousel",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "quotes",
    "quote card",
    "green theme",
    "dark green background",
    "teal",
    "three column",
    "card grid",
    "star rating",
    "5 star",
    "avatar",
    "author info",
    "client feedback",
    "webflow",
    "wegems",
    "agency",
    "landing page",
    "saas",
    "startup",
    "navigation arrows",
    "horizontal slider",
    "clients",
    "success stories",
  ],
  fontFamily: ["DM Serif Display", "Inter"],
};
