export const metadata = {
  imagePath: "agent-input/biography/slideframe.jpg",
  name: "slideframe",
  keywords: [
    "biography",
    "bio",
    "about",
    "about the author",
    "author",
    "profile",
    "personal",
    "portfolio",
    "designer",
    "developer",
    "two column",
    "split layout",
    "circular photo",
    "round avatar",
    "profile image",
    "social links",
    "social media",
    "twitter",
    "instagram",
    "linkedin",
    "dribbble",
    "email",
    "contact",
    "light theme",
    "light gray background",
    "minimal",
    "minimalist",
    "clean design",
    "simple layout",
    "personal website",
    "landing page",
    "introduction",
    "professional",
    "creative",
    "typography",
    "type foundry",
    "web design",
    "berlin",
    "underlined links",
    "text links",
    "about section",
    "slideframe",
    "jonas pelzer",
  ],
  fontFamily: ["Inter"],
};
