export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-23.jpg",
  name: "landingfolio-hero-23",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "SaaS",
    "dashboard preview",
    "CTA",
    "call to action",
    "dual buttons",
    "primary button",
    "secondary button",
    "navigation",
    "header",
    "startup",
    "marketing",
    "conversion",
    "landingfolio",
    "business",
    "developer tools",
    "free trial",
    "demo",
    "watch demo",
    "light theme",
    "clean design",
    "minimal",
    "professional",
    "B2B",
    "analytics dashboard",
    "admin panel",
    "UI kit",
    "component library",
    "serif headline",
    "split layout",
    "product showcase",
    "app preview",
    "software",
    "web app",
    "clarity UI",
    "dashboard mockup",
  ],
  fontFamily: ["Inter", "Instrument Serif"],
};
