export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-31.jpg",
  name: "landingfolio-hero-31",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "email marketing",
    "SaaS",
    "security",
    "secure email",
    "email tool",
    "marketing tool",
    "ClarityUI",
    "two column",
    "split layout",
    "image left",
    "text right",
    "statistics card",
    "stats overlay",
    "floating card",
    "wifi icon",
    "signal icon",
    "badge",
    "tag",
    "CTA",
    "call to action",
    "discovery call",
    "free trial",
    "navigation",
    "header",
    "startup",
    "B2B",
    "professional",
    "clean design",
    "modern",
    "minimal",
    "white background",
    "blue accent",
    "blue button",
    "rounded button",
    "woman photo",
    "person photo",
    "landingfolio",
    "business",
    "enterprise",
    "secured emails",
    "weekly stats",
  ],
  fontFamily: ["Inter"],
};
