export const metadata = {
  imagePath: "agent-input/testimonial-slider/done.jpg",
  name: "testimonial-slider",
  keywords: [
    "testimonial",
    "testimonials",
    "slider",
    "carousel",
    "reviews",
    "customer reviews",
    "social proof",
    "quotes",
    "feedback",
    "customer feedback",
    "food",
    "beverage",
    "protein drink",
    "health",
    "nutrition",
    "warm theme",
    "cream background",
    "beige",
    "pink card",
    "orange card",
    "brown accent",
    "decorative images",
    "chocolate",
    "strawberry",
    "fruit",
    "navigation arrows",
    "card slider",
    "three cards",
    "serif italic",
    "playfair display",
    "modern",
    "organic",
    "natural",
    "wellness",
    "product testimonials",
    "landing page",
    "section",
  ],
  fontFamily: ["Inter", "Playfair Display"],
};
