export const metadata = {
  imagePath: "agent-input/beautiful-sections/60-logo-tips-showcase.png",
  name: "logo-tips-showcase",
  keywords: [
    "logo",
    "showcase",
    "portfolio",
    "brand",
    "branding",
    "design",
    "mockup",
    "product",
    "carousel",
    "gallery",
    "horizontal-scroll",
    "cards",
    "company",
    "client",
    "work",
    "case-study",
    "impact",
    "value",
    "creative",
    "agency",
    "designer",
  ],
  fontFamily: ["Inter"],
};
