export const metadata = {
  imagePath: "agent-input/contact-form/milliners-yard.jpg",
  name: "milliners-yard",
  keywords: [
    "contact form",
    "register interest",
    "real estate",
    "property",
    "apartment",
    "rental",
    "lease",
    "brochure download",
    "lead capture",
    "inquiry form",
    "burgundy",
    "wine color",
    "dark red",
    "coral accent",
    "salmon pink",
    "elegant",
    "luxury",
    "premium",
    "serif font",
    "italic heading",
    "underline input",
    "dropdown select",
    "textarea",
    "message form",
    "bedroom selection",
    "move in date",
    "preferred rent",
    "phone number",
    "email",
    "first name",
    "last name",
    "decorative stripes",
    "geometric pattern",
    "circular frame",
    "building image",
    "property listing",
    "residential",
    "housing",
    "landing page",
    "sign up",
    "newsletter",
    "subscription",
    "interest registration",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
