export const metadata = {
  imagePath: "agent-input/testimonial-tweets/geneva.jpg",
  name: "geneva-testimonial-tweets",
  keywords: [
    "testimonial",
    "twitter",
    "tweets",
    "social proof",
    "reviews",
    "customer feedback",
    "geneva",
    "groups",
    "community",
    "masonry",
    "grid",
    "cards",
    "user quotes",
    "x",
    "social media",
    "white background",
    "light theme",
    "mission statement",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
