export const metadata = {
  imagePath: "agent-input/contact-form/resync-bio.jpg",
  name: "resync-bio-contact",
  keywords: [
    "contact form",
    "contact",
    "form",
    "lead capture",
    "lead generation",
    "email form",
    "message form",
    "inquiry form",
    "get in touch",
    "sync",
    "resync",
    "bio",
    "submit form",
    "first name",
    "last name",
    "email input",
    "message textarea",
    "dropdown select",
    "privacy policy",
    "light theme",
    "minimal design",
    "centered layout",
    "gray background",
    "green badge",
    "SaaS",
    "startup",
    "business contact",
    "customer inquiry",
    "support form",
    "contact us",
    "input fields",
    "form validation",
  ],
  fontFamily: ["Inter"],
};
