export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-11.jpg",
  name: "landingfolio-hero-11",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "light theme",
    "code review",
    "code feedback",
    "developers",
    "programmers",
    "coding",
    "code editor",
    "IDE",
    "browser mockup",
    "chat",
    "comments",
    "collaboration",
    "team",
    "SaaS",
    "developer tools",
    "prisma",
    "database",
    "schema",
    "navigation",
    "header",
    "CTA",
    "call to action",
    "button",
    "avatar group",
    "social proof",
    "startup",
    "rareblocks",
    "meaningful feedback",
    "serif italic",
    "modern",
    "clean",
    "minimal",
    "iOS app",
    "download",
  ],
  fontFamily: ["Inter"],
};
