export const metadata = {
  imagePath: "agent-input/testimonial-slider/nvgt.jpg",
  name: "nvgt-testimonial-slider",
  keywords: [
    "testimonial",
    "testimonials",
    "slider",
    "carousel",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "quotes",
    "quote card",
    "black theme",
    "dark theme",
    "dark mode",
    "three column",
    "grid layout",
    "italic headline",
    "serif font",
    "nvgt",
    "brands",
    "company logos",
    "navigation arrows",
    "avatar",
    "author info",
    "pill badge",
    "badge",
    "landing page",
    "saas",
    "startup",
    "agency",
    "helping brands",
    "goals",
    "change",
    "sentry",
    "capital dept",
    "limbo",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
