export const metadata = {
  imagePath: "agent-input/testimonial-tweets/reflect.jpg",
  name: "reflect-testimonial-tweets",
  keywords: [
    "testimonial",
    "twitter",
    "tweets",
    "social proof",
    "reviews",
    "customer feedback",
    "reflect",
    "masonry layout",
    "grid layout",
    "3 column",
    "dark theme",
    "dark mode",
    "purple gradient",
    "teal gradient",
    "cards",
    "user quotes",
    "x",
    "social media",
    "note-taking app",
    "thinkers",
    "loved by thinkers",
    "avatar",
    "username",
    "handle",
    "neural network",
    "back-linking",
    "knowledge worker",
    "productivity",
    "note taking",
  ],
  fontFamily: ["Inter"],
};
