export const metadata = {
  imagePath: "agent-input/before-after/glow-team.jpg",
  name: "glow-team",
  keywords: [
    "before after",
    "comparison",
    "pros cons",
    "with without",
    "feature comparison",
    "benefits",
    "advantages",
    "disadvantages",
    "checklist",
    "check mark",
    "x mark",
    "two column",
    "side by side",
    "light theme",
    "white background",
    "lime green",
    "green accent",
    "startup",
    "outcomes",
    "team",
    "agency",
    "design agency",
    "product design",
    "service comparison",
    "value proposition",
    "landing page",
    "marketing",
    "saas",
    "clean design",
    "minimal",
    "professional",
    "card layout",
    "rounded cards",
    "trust signals",
    "social proof",
    "glow",
    "trial",
    "investment",
    "transparency",
    "ai tools",
    "budget",
  ],
  fontFamily: ["Inter"],
};
