export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-12.jpg",
  name: "landingfolio-hero-12",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "personal brand",
    "personal website",
    "writer",
    "blogger",
    "NFT",
    "crypto",
    "blockchain",
    "content creator",
    "author",
    "blog",
    "latest picks",
    "articles",
    "featured posts",
    "profile",
    "portrait",
    "photo hero",
    "asymmetric layout",
    "decorative elements",
    "call to action",
    "CTA",
    "navigation",
    "header",
    "light theme",
    "clean design",
    "modern",
    "creative",
    "purple accent",
    "read blog",
    "email list",
    "newsletter",
    "services",
    "collections",
    "clarity ui",
    "landingfolio",
  ],
  fontFamily: ["Inter"],
};
