export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-16.jpg",
  name: "landingfolio-hero-16",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "light theme",
    "light mode",
    "designer community",
    "designers",
    "newsletter",
    "email subscription",
    "email signup",
    "blog cards",
    "article cards",
    "card carousel",
    "card slider",
    "navigation",
    "header",
    "CTA",
    "call to action",
    "SaaS",
    "startup",
    "ClarityUI",
    "modern",
    "minimal",
    "clean",
    "white background",
    "community",
    "content platform",
    "photography",
    "reading time",
    "growth",
    "sparkle icon",
    "lightning icon",
    "emoji",
    "weekly updates",
    "subscribe form",
    "input field",
  ],
  fontFamily: ["Inter"],
};
