export const metadata = {
  imagePath: "agent-input/before-after/glow-guide.jpg",
  name: "glow-guide",
  keywords: [
    "hero",
    "beauty",
    "skincare",
    "before after",
    "progress tracking",
    "photo comparison",
    "mobile app",
    "iPhone mockup",
    "face analysis",
    "skin tracker",
    "wellness",
    "health app",
    "two column",
    "clean design",
    "white background",
    "light theme",
    "minimal",
    "badge",
    "headline",
    "subheadline",
    "CTA",
    "product showcase",
    "app landing",
    "day counter",
    "facial markers",
    "glow",
    "skincare routine",
    "beauty tech",
    "self care",
    "SaaS landing",
    "feature highlight",
  ],
  fontFamily: ["Inter"],
};
