export const metadata = {
  imagePath: "agent-input/feature-carousel/the-other-glasses.jpg",
  name: "product-feature-showcase",
  keywords: [
    "product",
    "feature",
    "showcase",
    "carousel",
    "scroll",
    "glasses",
    "eyewear",
    "detail",
    "specification",
    "highlight",
    "sidebar",
    "navigation",
    "sticky",
    "elegant",
    "minimal",
    "luxury",
    "product-detail",
    "feature-list",
    "interactive",
  ],
  fontFamily: ["Playfair Display", "Inter"],
};
