export const metadata = {
  imagePath: "agent-input/testimonial-tweets/texts.jpg",
  name: "texts-testimonial-tweets",
  keywords: [
    "testimonial",
    "twitter",
    "tweets",
    "social proof",
    "reviews",
    "customer feedback",
    "texts.com",
    "messaging app",
    "unified inbox",
    "cards",
    "user quotes",
    "x",
    "social media",
    "light theme",
    "white background",
    "twitter cards",
    "tweet wall",
    "social testimonials",
    "iphone mockup",
    "before after",
    "app showcase",
    "dms",
    "imessage",
    "whatsapp",
    "signal",
    "telegram",
    "messaging",
    "productivity",
  ],
  fontFamily: ["Inter"],
};
