export const metadata = {
  imagePath: "agent-input/contact-form/yoga-with-tanya.jpg",
  name: "yoga-with-tanya",
  keywords: [
    "contact form",
    "contact section",
    "get in touch",
    "yoga",
    "wellness",
    "fitness",
    "instructor",
    "consultation",
    "introductory call",
    "booking form",
    "message form",
    "email form",
    "name email message",
    "submit form",
    "two column layout",
    "minimal design",
    "light gray background",
    "beige button",
    "warm neutral",
    "serif heading",
    "elegant",
    "personal trainer",
    "coach",
    "schedule call",
    "inquiry form",
    "lead form",
    "contact us",
  ],
  fontFamily: ["Playfair Display", "Inter"],
};
