export const metadata = {
  imagePath: "agent-input/contact-form/stickbird-studio.jpg",
  name: "stickbird-studio",
  keywords: [
    "contact form",
    "contact us",
    "creative agency",
    "studio contact",
    "lead form",
    "inquiry form",
    "project inquiry",
    "budget form",
    "timeline form",
    "service selection",
    "gray background",
    "minimal form",
    "clean design",
    "two column layout",
    "split layout",
    "headline left",
    "form right",
    "dropdown select",
    "textarea",
    "submit button",
    "black button",
    "rounded inputs",
    "white inputs",
    "gray theme",
    "neutral theme",
  ],
  fontFamily: ["Inter"],
};
