export const metadata = {
  imagePath: "agent-input/contact-form/obliques.jpg",
  name: "obliques",
  keywords: [
    "contact form",
    "meeting request",
    "dark theme",
    "lime green",
    "neon accent",
    "underline input",
    "minimal form",
    "italic heading",
    "two column layout",
    "business inquiry",
    "lead capture",
    "first meeting",
    "schedule meeting",
    "contact us",
    "get in touch",
    "project inquiry",
    "consulting",
    "agency",
    "professional",
    "modern",
    "dark mode",
    "olive background",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
