export const metadata = {
  imagePath: "agent-input/contact-form/anett-weber.jpg",
  name: "anett-weber",
  keywords: [
    "contact",
    "contact form",
    "form",
    "contact section",
    "get in touch",
    "message form",
    "email form",
    "name input",
    "email input",
    "message textarea",
    "privacy policy",
    "toggle switch",
    "send button",
    "submit form",
    "purple theme",
    "dark purple",
    "indigo",
    "violet background",
    "italic title",
    "serif heading",
    "instagram",
    "social link",
    "email link",
    "two column",
    "side by side",
    "designer portfolio",
    "creative contact",
    "minimal form",
    "modern form",
    "landing page",
    "section",
  ],
  fontFamily: ["Inter", "Playfair Display"],
};
