export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-4.jpg",
  name: "landingfolio-hero-4",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "code editor",
    "IDE",
    "developer tools",
    "programming",
    "coding",
    "syntax highlighting",
    "HTML",
    "web development",
    "light theme",
    "light background",
    "navigation bar",
    "call to action",
    "CTA",
    "testimonial",
    "review",
    "star rating",
    "user review",
    "rareblocks",
    "landingfolio",
    "split layout",
    "two column",
    "code preview",
    "data table",
    "dark table",
    "browser mockup",
    "decorative arrows",
    "rainbow gradient",
  ],
  fontFamily: ["Inter"],
};
