export const metadata = {
  imagePath: "agent-input/beautiful-sections/rysa-pricing.png",
  name: "rysa-pricing",
  keywords: [
    "pricing",
    "pricing table",
    "pricing cards",
    "subscription",
    "plans",
    "tier",
    "saas",
    "monthly",
    "yearly",
    "billing toggle",
    "early access",
    "discount",
    "save",
    "wardrobe",
    "styling",
    "fashion",
    "popular",
    "badge",
    "cta",
    "call to action",
    "features list",
    "checkmark",
    "white background",
    "light theme",
    "minimalist",
    "clean design",
  ],
  fontFamily: ["Inter"],
};
