export const metadata = {
  imagePath: "agent-input/contact-form/coding-bio.jpg",
  name: "coding-bio",
  keywords: [
    "contact form",
    "contact",
    "form",
    "bio",
    "coding",
    "coding bio",
    "submit",
    "input",
    "email",
    "company",
    "message",
    "first name",
    "last name",
    "3d cube",
    "geometric",
    "decorative",
    "minimalist",
    "clean",
    "light theme",
    "cream background",
    "beige",
    "yellow accent",
    "lime",
    "professional",
    "business",
    "inquiry",
    "reach out",
    "get in touch",
    "SaaS",
    "startup",
    "modern",
    "creative",
    "tech",
    "technology",
    "developer",
    "software",
    "agency",
  ],
  fontFamily: ["DM Serif Display", "Inter"],
};
