export const metadata = {
  imagePath: "agent-input/contact-form/chantal-hoahing.jpg",
  name: "chantal-hoahing",
  keywords: [
    "contact form",
    "postcard",
    "postcard style",
    "postal card",
    "letter",
    "mail",
    "email form",
    "newsletter",
    "subscribe",
    "contact",
    "message form",
    "minimal",
    "clean",
    "white",
    "light theme",
    "stamp",
    "Netherlands",
    "Dutch",
    "personal contact",
    "freelancer",
    "designer contact",
    "creative",
    "two column",
    "split layout",
    "greeting",
    "Hi Chantal",
    "handwritten feel",
    "simple form",
    "elegant",
    "name email form",
    "submit form",
    "business card style",
    "rounded corners",
    "card layout",
    "vintage stamp",
  ],
  fontFamily: ["Inter"],
};
