export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-25.jpg",
  name: "landingfolio-hero-25",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "SaaS",
    "website builder",
    "webflow",
    "copy paste",
    "components",
    "design blocks",
    "UI kit",
    "testimonial",
    "quote",
    "CTA",
    "call to action",
    "two column",
    "split layout",
    "image hero",
    "photo hero",
    "professional",
    "clean design",
    "modern",
    "minimal",
    "white background",
    "blue accent",
    "checklist",
    "feature list",
    "benefits",
    "social proof",
    "customer quote",
    "navigation",
    "header",
    "startup",
    "B2B",
    "developer tools",
    "no-code",
    "low-code",
    "clarity ui",
    "landingfolio",
  ],
  fontFamily: ["Inter"],
};
