export const metadata = {
  imagePath: "agent-input/contact-form/ordinaryfolks.jpg",
  name: "ordinaryfolks-contact-form",
  keywords: [
    "contact form",
    "event form",
    "launch event",
    "contact us",
    "message form",
    "email form",
    "dark theme",
    "minimal design",
    "black background",
    "white border",
    "outlined inputs",
    "send message",
    "inquiry form",
    "bold italic title",
    "uppercase labels",
    "centered layout",
    "event registration",
    "event inquiry",
  ],
  fontFamily: ["Inter"],
};
