export const metadata = {
  imagePath: "agent-input/feature-carousel/automator-for-figma.jpg",
  name: "figma-feature-tabs",
  keywords: [
    "figma",
    "feature",
    "tabs",
    "automation",
    "plugin",
    "design specs",
    "import",
    "airtable",
    "placeholders",
    "drag and drop",
    "workflow",
    "productivity",
    "design tools",
    "supercharge",
    "feature carousel",
    "tab navigation",
    "app preview",
    "macbook frame",
    "gradient border",
    "dark theme",
    "saas",
    "landing page",
  ],
  fontFamily: ["Inter"],
};
