export const metadata = {
  imagePath: "agent-input/biography/fast-forward-freelance.jpg",
  name: "fast-forward-freelance",
  keywords: [
    "biography",
    "bio",
    "profile",
    "personal",
    "about me",
    "portfolio",
    "designer",
    "web designer",
    "webflow",
    "developer",
    "freelancer",
    "freelance",
    "entrepreneur",
    "course",
    "online course",
    "education",
    "six-figure",
    "income",
    "business",
    "marketing",
    "light theme",
    "beige background",
    "cream background",
    "warm",
    "minimal",
    "minimalist",
    "clean design",
    "personal website",
    "landing page",
    "introduction",
    "professional",
    "creative",
    "consultant",
    "highlight",
    "marker",
    "lime green",
    "accent color",
    "serif heading",
    "instrument serif",
    "two column footer",
    "avatar",
    "profile photo",
    "social link",
    "twitter",
    "x",
    "cta",
    "call to action",
    "storytelling",
    "narrative",
    "compelling",
    "grace",
    "meet the founder",
    "about section",
    "single column",
    "centered layout",
    "testimonial intro",
    "course creator",
    "content creator",
    "solopreneur",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
