export const metadata = {
  imagePath: "agent-input/feature-carousel/straple.jpg",
  name: "feature-tabs-hero",
  keywords: [
    "feature",
    "tabs",
    "hero",
    "headline",
    "designer",
    "startup",
    "agency",
    "work",
    "productivity",
    "dark",
    "carousel",
    "navigation",
    "landing",
    "section",
    "tabbed",
    "content",
    "switcher",
  ],
  fontFamily: ["Inter"],
};
