export const metadata = {
  imagePath: "agent-input/contact-form/virtu-digital.jpg",
  name: "virtu-digital",
  keywords: [
    "contact form",
    "contact section",
    "collaboration",
    "footer contact",
    "agency contact",
    "digital agency",
    "virtu digital",
    "form",
    "email form",
    "phone input",
    "name input",
    "submit form",
    "dark background",
    "navy blue",
    "indigo",
    "footer",
    "contact footer",
    "get in touch",
    "let's collaborate",
    "collaboration request",
    "business inquiry",
    "agency footer",
    "creative agency",
    "web agency",
    "design agency",
    "minimal form",
    "clean design",
    "professional",
    "corporate",
  ],
  fontFamily: ["Inter"],
};
