export const metadata = {
  imagePath: "agent-input/biography/ui-flip.jpg",
  name: "ui-flip",
  keywords: [
    "biography",
    "bio",
    "profile",
    "personal",
    "about me",
    "portfolio",
    "designer",
    "founder",
    "principal designer",
    "ui designer",
    "ux designer",
    "product designer",
    "freelancer",
    "agency",
    "design services",
    "saas",
    "web apps",
    "mobile apps",
    "landing pages",
    "e-commerce",
    "design systems",
    "logo branding",
    "light theme",
    "white background",
    "two column layout",
    "profile photo",
    "grayscale photo",
    "circular photo",
    "social links",
    "linkedin",
    "dribbble",
    "behance",
    "instagram",
    "services list",
    "checkmarks",
    "cta button",
    "see plans",
    "pricing",
    "yellow accent",
    "teal accent",
    "cyan accent",
    "wavy underline",
    "hello greeting",
    "wave emoji",
    "teamwork.com",
    "startup",
    "personal website",
    "introduction",
    "professional",
    "clean design",
    "minimal",
    "minimalist",
  ],
  fontFamily: ["DM Sans"],
};
