export const metadata = {
  imagePath: "agent-input/feature-carousel/magician-for-figma.jpg",
  name: "magic-wand-feature",
  keywords: [
    "feature",
    "showcase",
    "ai",
    "magic",
    "wand",
    "tabs",
    "navigation",
    "laptop",
    "mockup",
    "device",
    "phone",
    "mobile",
    "icon",
    "generator",
    "text-to-icon",
    "copywriting",
    "text-to-image",
    "figma",
    "plugin",
    "design",
    "tool",
    "saas",
    "landing",
    "hero",
    "dark",
    "carousel",
    "slider",
  ],
  fontFamily: ["Inter"],
};
