export const metadata = {
  imagePath: "agent-input/dribble-hero/a5g.png",
  name: "a5g-hero",
  keywords: [
    "hero",
    "landing page",
    "automation",
    "AI",
    "artificial intelligence",
    "intelligent automation",
    "dark theme",
    "black background",
    "wave effect",
    "abstract waves",
    "gradient waves",
    "blue purple gradient",
    "tech",
    "technology",
    "saas",
    "startup",
    "enterprise",
    "business",
    "cta",
    "call to action",
    "free trial",
    "logo strip",
    "company logos",
    "trusted by",
    "navigation",
    "header",
    "modern",
    "futuristic",
    "a5g",
    "process automation",
    "digital transformation",
  ],
  fontFamily: ["Inter"],
};
