export const metadata = {
  imagePath: "agent-input/testimonial-slider/adith-narein.jpg",
  name: "adith-narein-testimonial",
  keywords: [
    "testimonial",
    "testimonials",
    "slider",
    "carousel",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "quotes",
    "light theme",
    "white background",
    "gray cards",
    "horizontal layout",
    "multi-card",
    "avatar icon",
    "script font",
    "cursive names",
    "hear from people",
    "worked with",
    "portfolio",
    "freelancer",
    "designer testimonial",
    "client feedback",
    "professional",
    "minimal",
    "clean design",
    "adith narein",
    "kuberks",
    "dusk security",
    "computahi",
    "handwritten",
    "personal branding",
  ],
  fontFamily: ["Inter", "Dancing Script"],
};
