export const metadata = {
  imagePath: "agent-input/feature-carousel/screen-studio.jpg",
  name: "feature-showcase-sections",
  keywords: [
    "feature showcase",
    "screen recording",
    "automatic zoom",
    "professional animations",
    "cursor movement",
    "video editing",
    "product features",
    "feature list",
    "dark theme",
    "two column layout",
    "feature highlight",
    "software features",
    "demo features",
    "screen studio",
    "recording software",
    "animation effects",
    "cursor effects",
    "video demo",
    "feature sections",
    "product landing",
  ],
  fontFamily: ["Inter"],
};
