export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-17.jpg",
  name: "landingfolio-hero-17",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "fintech",
    "credit card",
    "developer",
    "developers",
    "banking",
    "financial",
    "payment",
    "visa",
    "card",
    "email signup",
    "email capture",
    "newsletter",
    "CTA",
    "call to action",
    "navigation",
    "header",
    "startup",
    "marketing",
    "conversion",
    "rareblocks",
    "landingfolio",
    "business",
    "statistics",
    "stats",
    "cards delivered",
    "transaction",
    "light theme",
    "clean design",
    "minimal",
    "professional",
    "B2B",
    "SaaS",
    "free card",
    "sign up form",
    "input field",
  ],
  fontFamily: ["Inter"],
};
