export const metadata = {
  imagePath: "agent-input/biography/daniel-sun.jpg",
  name: "daniel-sun",
  keywords: [
    "biography",
    "bio",
    "profile",
    "personal",
    "about me",
    "portfolio",
    "designer",
    "developer",
    "branding",
    "marketing",
    "digital experience",
    "founder",
    "startup",
    "VC-backed",
    "venture capital",
    "product designer",
    "polaroid",
    "photo",
    "family",
    "light theme",
    "white background",
    "minimal",
    "minimalist",
    "clean design",
    "personal website",
    "landing page",
    "introduction",
    "professional",
    "creative",
    "agency",
    "freelancer",
    "consultant",
    "Ukraine",
    "Portugal",
    "Porto",
    "Kharkiv",
    "international",
    "global",
    "handwriting",
    "cursive",
    "script font",
    "photo collage",
    "snapshot",
    "instant photo",
    "vintage photo",
    "two column",
    "horizontal layout",
    "side by side",
    "storytelling",
    "narrative",
    "compelling",
    "investor pitch",
  ],
  fontFamily: ["Caveat", "Inter"],
};
