export const metadata = {
  imagePath: "agent-input/feature-carousel/ogkit.jpg",
  name: "ogkit-feature-showcase",
  keywords: [
    "feature",
    "showcase",
    "open graph",
    "og image",
    "html",
    "developer",
    "code editor",
    "preview",
    "meta tags",
    "social media",
    "og:image",
    "feature cards",
    "three columns",
    "developer tools",
    "website assets",
    "tech stack",
    "integration",
    "browser preview",
    "code snippet",
    "landing page section",
  ],
  fontFamily: ["Inter"],
};
