export const metadata = {
  imagePath: "agent-input/biography/juho.jpg",
  name: "juho",
  keywords: [
    "biography",
    "bio",
    "profile",
    "personal",
    "about me",
    "about section",
    "portfolio",
    "designer",
    "finnish designer",
    "nordic",
    "scandinavia",
    "norway",
    "minimal",
    "minimalist",
    "clean design",
    "white background",
    "light theme",
    "two column",
    "side by side",
    "profile image",
    "portrait",
    "personal website",
    "landing page",
    "introduction",
    "professional",
    "freelancer",
    "independent designer",
    "subscription service",
    "design subscription",
    "self introduction",
    "simple layout",
    "sans-serif",
    "modern typography",
    "bold heading",
    "gray text",
    "subtle design",
    "elegant",
    "professional bio",
  ],
  fontFamily: ["Inter"],
};
