export const metadata = {
  imagePath: "agent-input/contact-form/hpq-frankfurt.jpg",
  name: "hpq-frankfurt",
  keywords: [
    "contact form",
    "contact us",
    "contact page",
    "minimal form",
    "elegant form",
    "beige background",
    "warm background",
    "cream background",
    "underline inputs",
    "minimal inputs",
    "paper airplane",
    "send message",
    "message form",
    "inquiry form",
    "corporate contact",
    "business contact",
    "press contact",
    "social links",
    "linkedin",
    "instagram",
    "two column form",
    "split form layout",
    "italic heading",
    "serif heading",
    "B&L Gruppe",
    "Frankfurt",
    "HPQ",
    "real estate",
    "property",
    "German company",
    "European style",
  ],
  fontFamily: ["Playfair Display", "Inter"],
};
