export const metadata = {
  imagePath: "agent-input/testimonial-tweets/sizzy.jpg",
  name: "sizzy-testimonial-tweets",
  keywords: [
    "testimonial",
    "twitter",
    "tweets",
    "social proof",
    "reviews",
    "customer feedback",
    "sizzy",
    "responsive design",
    "developer tools",
    "web development",
    "grid layout",
    "masonry",
    "cards",
    "user quotes",
    "x",
    "social media",
    "purple gradient",
    "dark theme",
  ],
  fontFamily: ["Inter"],
};
