export const metadata = {
  imagePath: "agent-input/biography/metoda-teczowki.jpg",
  name: "metoda-teczowki",
  keywords: [
    "biography",
    "bio",
    "about",
    "about me",
    "author",
    "profile",
    "personal",
    "dark theme",
    "black background",
    "sidebar",
    "vertical text",
    "rotated text",
    "polish",
    "klosinski",
    "jacek klosinski",
    "portrait",
    "photo",
    "social media",
    "facebook",
    "youtube",
    "spotify",
    "social icons",
    "two column",
    "split layout",
    "minimalist",
    "modern",
    "clean",
    "professional",
    "introduction",
    "personal website",
    "landing page",
    "blog",
    "author page",
    "writer",
    "coach",
    "motivational",
    "self-improvement",
    "productivity",
    "work-life balance",
    "sans-serif",
    "circular icons",
    "grid layout",
  ],
  fontFamily: ["Inter"],
};
