export const metadata = {
  imagePath: "agent-input/landingfolio-stats/stats-9.jpg",
  name: "stats-9",
  keywords: [
    "stats",
    "statistics",
    "numbers",
    "metrics",
    "data",
    "saas",
    "landing page",
    "two column",
    "grid",
    "satisfied clients",
    "downloads",
    "projects",
    "awards",
    "counter",
    "achievements",
    "company stats",
    "business metrics",
    "clean design",
    "minimal",
    "professional",
    "light theme",
    "white background",
    "blue accent",
  ],
  fontFamily: ["Inter"],
};
