export const metadata = {
  imagePath: "agent-input/feature-carousel/reflect.jpg",
  name: "tools-for-thought-section",
  keywords: [
    "tools for thought",
    "knowledge graph",
    "backlink",
    "note taking",
    "personal knowledge management",
    "PKM",
    "reflect app",
    "sync",
    "kindle integration",
    "REST API",
    "feature cards",
    "node graph",
    "network visualization",
    "dark theme",
    "two column layout",
    "feature section",
    "product landing",
    "SaaS landing",
    "brain mapping",
    "thought organization",
    "note connections",
    "profile card",
    "glass card",
    "animated nodes",
  ],
  fontFamily: ["Inter"],
};
