export const metadata = {
  imagePath: "agent-input/contact-form/bondfire-inc.jpg",
  name: "bondfire-inc",
  keywords: [
    "contact form",
    "contact page",
    "project inquiry",
    "inquiry form",
    "design studio",
    "technology studio",
    "multidisciplinary",
    "e-commerce",
    "branding",
    "optimization",
    "minimal design",
    "typography",
    "typewriter font",
    "monospace",
    "grid layout",
    "three column",
    "checkbox form",
    "email form",
    "company info",
    "footer links",
    "bondfire",
    "ojai california",
    "submit form",
    "white background",
    "clean design",
    "professional",
  ],
  fontFamily: ["Courier Prime"],
};
