export const metadata = {
  imagePath: "agent-input/contact-form/youballin.jpg",
  name: "youballin",
  keywords: [
    "contact form",
    "enquiry form",
    "lead capture",
    "signup form",
    "registration",
    "colorful",
    "vibrant",
    "purple",
    "blue background",
    "pill input",
    "rounded form",
    "gradient",
    "blob background",
    "organic shapes",
    "country dropdown",
    "social media handle",
    "email capture",
    "send enquiry",
    "jump in",
    "call to action",
    "CTA",
    "modern design",
    "fun design",
    "playful",
    "lime accent",
    "mint accent",
  ],
  fontFamily: ["DM Serif Display", "Inter"],
};
