export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-18.jpg",
  name: "landingfolio-hero-18",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "bakery",
    "baking",
    "bread",
    "sourdough",
    "artisan",
    "online course",
    "cooking class",
    "food",
    "culinary",
    "subscription",
    "monthly pricing",
    "dark theme",
    "moody",
    "elegant",
    "full screen background",
    "background image",
    "CTA",
    "call to action",
    "dual buttons",
    "watch trailer",
    "video",
    "play button",
    "navigation",
    "header",
    "sign up",
    "courses",
    "education",
    "learning platform",
    "cooking tutorial",
    "recipe",
    "masterclass",
    "serif font",
    "italic headline",
    "premium",
    "professional",
    "landingfolio",
  ],
  fontFamily: ["Inter", "Instrument Serif"],
};
