name: Registry Component Metadata Bug
description: Report incorrect metadata for a registry component
title: "[Registry Metadata] "
labels: ["bug", "registry-metadata"]
body:
  - type: input
    id: component-id
    attributes:
      label: Component ID
      description: The ID of the registry component (e.g., clerk-com-hero-1)
      placeholder: clerk-com-hero-1
    validations:
      required: true

  - type: textarea
    id: incorrect-metadata
    attributes:
      label: Incorrect Metadata
      description: Which metadata field(s) are incorrect and what are the current values?
      placeholder: |
        Field: title
        Current value: "Hero Section"
    validations:
      required: true

  - type: textarea
    id: expected-metadata
    attributes:
      label: Expected Metadata
      description: What should the correct values be?
      placeholder: |
        Field: title
        Expected value: "Main Hero Section"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information or screenshots
    validations:
      required: false
