export const metadata = {
  imagePath: "agent-input/contact-form/pear.jpg",
  name: "pear",
  keywords: [
    "contact form",
    "contact us",
    "get in touch",
    "reach out",
    "questions",
    "inquiry",
    "message form",
    "email form",
    "support form",
    "team contact",
    "two column layout",
    "split layout",
    "image form",
    "warm design",
    "cream background",
    "beige background",
    "orange accent",
    "coral button",
    "rounded button",
    "pill button",
    "decorative shapes",
    "geometric shapes",
    "purple semicircle",
    "orange semicircle",
    "team photo",
    "business contact",
    "professional",
    "friendly",
    "welcoming",
    "modern form",
    "clean form",
    "minimal form",
    "first name",
    "last name",
    "phone number",
    "message textarea",
    "submit button",
    "underline text",
    "highlighted text",
  ],
  fontFamily: ["Inter"],
};
