export const metadata = {
  imagePath: "agent-input/biography/mike-mcalister.jpg",
  name: "mike-mcalister-bio",
  keywords: [
    "biography",
    "bio",
    "about me",
    "personal",
    "profile",
    "hero",
    "introduction",
    "two column",
    "split layout",
    "gradient background",
    "purple gradient",
    "blue gradient",
    "white section",
    "profile photo",
    "headshot",
    "signature",
    "handwritten",
    "designer",
    "developer",
    "engineer",
    "freelancer",
    "portfolio",
    "personal website",
    "landing page",
    "human centered",
    "problem solver",
    "wordpress",
    "digital products",
    "creator",
    "serif heading",
    "italic heading",
    "dm serif display",
    "inter font",
    "professional",
    "modern",
    "clean design",
    "mike mcalister",
  ],
  fontFamily: ["DM Serif Display", "Inter"],
};
