export const metadata = {
  imagePath: "agent-input/contact-form/superfriendly.jpg",
  name: "superfriendly-contact",
  keywords: [
    "contact form",
    "contact section",
    "get in touch",
    "inquiry form",
    "booking form",
    "project booking",
    "dark theme",
    "dark mode",
    "charcoal background",
    "gradient text",
    "colorful logo",
    "holographic",
    "agency contact",
    "design agency",
    "superfriendly",
    "lets build together",
    "social links",
    "instagram",
    "linkedin",
    "twitter",
    "email contact",
    "name input",
    "inquiry textarea",
    "lets talk button",
    "minimal form",
    "modern contact",
    "creative agency",
    "web design",
  ],
  fontFamily: ["Inter"],
};
