export const metadata = {
  imagePath: "agent-input/testimonial-tweets/10x-designers.jpg",
  name: "ten-x-designers-testimonial",
  keywords: [
    "testimonial",
    "twitter",
    "tweets",
    "social proof",
    "reviews",
    "customer feedback",
    "10x designers",
    "scattered layout",
    "cards",
    "user quotes",
    "x",
    "social media",
    "designer community",
    "light theme",
    "white background",
    "gray cards",
    "grid layout",
    "avatar",
    "profile picture",
    "handles",
    "tweet about us",
    "featured",
    "designer testimonials",
    "community feedback",
    "what designers say",
    "listen up",
    "badge",
    "pill badge",
    "cyan badge",
    "blue accent",
    "fade edges",
    "partially visible cards",
    "minimal design",
    "clean layout",
  ],
  fontFamily: ["Inter"],
};
