export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-34.jpg",
  name: "landingfolio-hero-34",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "bakery",
    "bread",
    "artisan",
    "bread making",
    "food",
    "restaurant",
    "cafe",
    "cooking",
    "baking",
    "culinary",
    "course",
    "masterclass",
    "tutorial",
    "video",
    "trailer",
    "play video",
    "dark theme",
    "black background",
    "centered content",
    "serif font",
    "italic",
    "elegant",
    "rustic",
    "warm",
    "organic",
    "natural",
    "CTA",
    "call to action",
    "outlined button",
    "play button",
    "navigation",
    "header",
    "minimal nav",
    "BakerStreet",
    "landingfolio",
    "video hero",
    "image hero",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
