export const metadata = {
  imagePath: "agent-input/biography/yianni-mathioudakis.jpg",
  name: "yianni-mathioudakis",
  keywords: [
    "biography",
    "bio",
    "about",
    "about me",
    "designer bio",
    "graphic designer",
    "multi-disciplinary designer",
    "creative bio",
    "portfolio bio",
    "personal story",
    "founder story",
    "co-founder",
    "education",
    "experience",
    "career",
    "skills",
    "expertise",
    "light theme",
    "cream background",
    "off-white",
    "minimal",
    "clean design",
    "serif font",
    "text section",
    "content block",
    "readable",
    "professional",
    "elegant",
    "underlined links",
    "inline links",
    "Maryland Institute College of Art",
    "MICA",
    "Fastspot",
    "DEEQ",
    "digital design",
    "motion graphics",
    "photography",
    "videography",
    "3D modeling",
    "creative partner",
    "design agency",
    "studio bio",
    "personal bio",
    "left aligned",
    "paragraph text",
    "body copy",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
