export const metadata = {
  imagePath: "agent-input/biography/design-gal-studio.jpg",
  name: "design-gal-studio",
  keywords: [
    "biography",
    "bio",
    "about",
    "about me",
    "introduction",
    "designer",
    "graphic designer",
    "design studio",
    "freelancer",
    "creative",
    "portfolio",
    "personal brand",
    "self introduction",
    "profile",
    "designer bio",
    "visual design",
    "UX design",
    "UI/UX",
    "design partner",
    "bento grid",
    "bento layout",
    "card layout",
    "colorful",
    "yellow",
    "lime green",
    "pink",
    "warm colors",
    "bright",
    "cheerful",
    "friendly",
    "professional",
    "trustworthy",
    "multi-disciplinary",
    "experience",
    "meet the designer",
    "nice to meet you",
    "light theme",
    "cream background",
    "beige",
    "modern",
    "rounded corners",
    "photo card",
    "profile photo",
    "feature cards",
    "value proposition",
    "services",
    "design services",
    "christine maggi",
    "design gal",
  ],
  fontFamily: ["DM Serif Display", "DM Sans"],
};
