export const metadata = {
  imagePath: "agent-input/contact-form/vivtel.jpg",
  name: "vivtel-contact-form",
  keywords: [
    "contact form",
    "contact us",
    "inquiry form",
    "lead capture",
    "business inquiry",
    "hotel",
    "hospitality",
    "franchise",
    "partnership",
    "VIVTEL",
    "dark theme",
    "navy blue",
    "gradient background",
    "two column layout",
    "elegant form",
    "enterprise contact",
    "B2B contact",
    "business development",
    "franchise inquiry",
    "hotel management",
    "property owners",
    "landlord contact",
    "investment inquiry",
    "journey of love",
    "italic serif headline",
    "professional form",
    "corporate contact",
  ],
  fontFamily: ["Playfair Display", "Inter"],
};
