export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-9.jpg",
  name: "landingfolio-hero-9",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "credit card",
    "fintech",
    "student",
    "student credit card",
    "banking",
    "finance",
    "payments",
    "dark theme",
    "dark mode",
    "teal",
    "mint green",
    "gradient cards",
    "floating cards",
    "credit card landing",
    "apply for free",
    "no yearly charges",
    "secured payment",
    "online payment",
    "CTA button",
    "call to action",
    "feature badges",
    "navigation",
    "navbar",
    "postcrafts",
    "simplified",
    "modern design",
    "financial services",
  ],
  fontFamily: ["DM Serif Display", "Inter"],
};
