export const metadata = {
  imagePath: "agent-input/beautiful-sections/60-logo-tips-hero.png",
  name: "60-logo-tips-hero",
  keywords: [
    "hero",
    "logo",
    "design",
    "tips",
    "book",
    "ebook",
    "course",
    "landing",
    "features",
    "icons",
    "grid",
    "educational",
    "product",
    "guide",
    "tutorial",
    "creative",
    "branding",
    "typography",
    "sketch",
    "presentation",
    "process",
  ],
  fontFamily: ["Inter"],
};
