export const metadata = {
  imagePath: "agent-input/contact-form/restless-rabbit-creative.jpg",
  name: "restless-rabbit-creative",
  keywords: [
    "contact form",
    "contact",
    "form",
    "get in touch",
    "inquiry",
    "message form",
    "email form",
    "send message",
    "creative agency",
    "agency contact",
    "minimal form",
    "underline input",
    "input fields",
    "name email message",
    "rabbit logo",
    "scattered pattern",
    "warm gray",
    "beige background",
    "serif heading",
    "location info",
    "phone number",
    "instagram link",
    "social media",
    "address",
    "business contact",
    "restless rabbit",
    "creative studio",
    "design agency",
    "landing page",
    "footer contact",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
