export const metadata = {
  imagePath: "agent-input/testimonial-slider/arkive.jpg",
  name: "arkive-testimonial-slider",
  keywords: [
    "testimonial",
    "testimonials",
    "slider",
    "carousel",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "quotes",
    "quote card",
    "green theme",
    "teal background",
    "dark theme",
    "two column",
    "split layout",
    "italic headline",
    "serif font",
    "arkive",
    "real people",
    "real feedback",
    "navigation arrow",
    "avatar",
    "author info",
    "pill badge",
    "badge",
    "landing page",
    "saas",
    "startup",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
