export const metadata = {
  imagePath: "agent-input/contact-form/well-designed.jpg",
  name: "well-designed-contact-form",
  keywords: [
    "contact form",
    "contact us",
    "enquiry form",
    "get in touch",
    "dark theme",
    "dark background",
    "gradient background",
    "teal",
    "navy",
    "hospitality",
    "hotel",
    "travel",
    "tourism",
    "greece",
    "two column",
    "split layout",
    "contact details",
    "address",
    "phone",
    "email",
    "social media",
    "instagram",
    "facebook",
    "minimal",
    "elegant",
    "luxury",
    "underline input",
    "border bottom input",
    "transparent input",
    "white button",
    "send enquiry",
    "name field",
    "email field",
    "message field",
    "well designed",
  ],
  fontFamily: ["Inter"],
};
