export const metadata = {
  imagePath: "agent-input/contact-form/awin.jpg",
  name: "awin",
  keywords: [
    "contact form",
    "contact",
    "form",
    "get in touch",
    "inquiry",
    "message",
    "email",
    "phone",
    "name",
    "privacy policy",
    "consent",
    "checkbox",
    "textarea",
    "input fields",
    "lead generation",
    "customer support",
    "business",
    "corporate",
    "professional",
    "clean design",
    "minimal",
    "light theme",
    "white background",
    "cyan accent",
    "turquoise",
    "sky blue",
    "decorative pattern",
    "curved lines",
    "awin",
    "send message",
    "CTA button",
    "pill button",
  ],
  fontFamily: ["Inter"],
};
