export const metadata = {
  imagePath: "agent-input/biography/mike-mcalister-2022.jpg",
  name: "mike-mcalister-2022",
  keywords: [
    "biography",
    "bio",
    "profile",
    "personal",
    "about me",
    "about section",
    "meet me",
    "introduction",
    "portfolio",
    "designer",
    "developer",
    "engineer",
    "software engineer",
    "principal engineer",
    "dark theme",
    "dark mode",
    "purple background",
    "navy background",
    "gradient background",
    "glass card",
    "glassmorphism",
    "two column",
    "profile image",
    "photo frame",
    "italic title",
    "serif title",
    "instrument serif",
    "inter font",
    "pink accent",
    "magenta links",
    "personal website",
    "landing page",
    "founder",
    "entrepreneur",
    "creator",
    "digital products",
    "wordpress",
    "wp engine",
    "career",
    "work experience",
    "professional",
    "tech",
    "hobbies",
    "interests",
    "creative",
    "elegant",
    "modern",
    "sophisticated",
    "warm tones",
    "soft dark",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
