export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-5.jpg",
  name: "landingfolio-hero-5",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "credit card",
    "fintech",
    "developer",
    "email signup",
    "email capture",
    "CTA",
    "call to action",
    "statistics",
    "stats",
    "rareblocks",
    "landingfolio",
    "saas",
    "startup",
    "modern",
    "clean",
    "minimal",
    "split layout",
    "two column",
    "image hero",
    "person photo",
    "woman",
    "credit card design",
    "visa",
    "fintech landing",
    "gradient card",
    "navigation bar",
    "header",
    "light theme",
    "white background"
  ],
  fontFamily: ["Inter"]
};
