export const metadata = {
  imagePath: "agent-input/before-after/resync-bio.jpg",
  name: "resync-bio",
  keywords: [
    "before after",
    "before-after",
    "comparison",
    "acceleration",
    "biotech",
    "biotechnology",
    "pharmaceutical",
    "drug discovery",
    "assay",
    "molecular structure",
    "molecule",
    "chemistry",
    "lab",
    "laboratory",
    "workflow",
    "automation",
    "CRO",
    "feature comparison",
    "benefits",
    "light theme",
    "purple gradient",
    "lavender",
    "pastel",
    "product showcase",
    "SaaS",
    "enterprise",
    "data flow",
    "analytics",
    "IC50",
    "readout",
    "tier 2 assay",
    "two column layout",
    "split layout",
    "card UI",
    "feature list",
    "resync",
    "bio",
    "science",
    "research",
  ],
  fontFamily: ["Inter"],
};
