export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-1.jpg",
  name: "landingfolio-hero-1",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "SaaS",
    "email campaign",
    "email marketing",
    "dashboard preview",
    "browser mockup",
    "CTA",
    "call to action",
    "dual buttons",
    "primary button",
    "secondary button",
    "navigation",
    "header",
    "startup",
    "marketing",
    "conversion",
    "rareblocks",
    "landingfolio",
    "business",
    "developer tools",
    "free trial",
    "demo",
    "watch demo",
    "light theme",
    "clean design",
    "minimal",
    "professional",
    "B2B",
    "analytics dashboard",
  ],
  fontFamily: ["Inter"],
};
