export const metadata = {
  imagePath: "agent-input/biography/anesh-kangutkar.jpg",
  name: "anesh-kangutkar-bio",
  keywords: [
    "about me",
    "about section",
    "bio",
    "biography",
    "personal",
    "portfolio",
    "designer",
    "developer",
    "creative",
    "dark theme",
    "dark mode",
    "minimal",
    "minimalist",
    "bold typography",
    "italic",
    "orange accent",
    "terracotta",
    "rust color",
    "circular button",
    "rotating text",
    "download resume",
    "resume button",
    "cv",
    "curriculum vitae",
    "statistics",
    "stats",
    "years experience",
    "projects count",
    "two column",
    "split layout",
    "hero section",
    "introduction",
    "self introduction",
    "personal branding",
    "freelancer",
    "agency",
    "digital experience",
    "brand design",
    "ui designer",
    "ux designer",
    "web designer",
    "modern",
    "trendy",
    "satoshi font",
    "uppercase",
    "tracking wide",
    "anesh kangutkar",
  ],
  fontFamily: ["Satoshi Variable", "Inter"],
};
