export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-30.jpg",
  name: "landingfolio-hero-30",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "SaaS",
    "startup",
    "growth",
    "blog",
    "articles",
    "featured articles",
    "content",
    "writing",
    "split layout",
    "two column",
    "dark background",
    "navy",
    "grid pattern",
    "gradient button",
    "CTA",
    "call to action",
    "article cards",
    "blog cards",
    "image cards",
    "featured content",
    "navigation",
    "header",
    "clarity ui",
    "professional",
    "modern",
    "clean design",
    "lightning icon",
    "bolt icon",
    "pink gradient",
    "cyan gradient",
    "multi-color gradient",
    "landingfolio",
  ],
  fontFamily: ["Inter"],
};
