export const metadata = {
  imagePath: "agent-input/contact-form/finnian-sturdy.jpg",
  name: "finnian-sturdy",
  keywords: [
    "contact form",
    "contact section",
    "freelancer",
    "availability",
    "booking",
    "inquiry form",
    "project inquiry",
    "scope of work",
    "lead generation",
    "minimal design",
    "light theme",
    "gray background",
    "underline inputs",
    "textarea",
    "email copy",
    "ASCII art",
    "chef illustration",
    "cooking metaphor",
    "Q4 availability",
    "let's get cooking",
    "send message",
    "copy email",
    "italic heading",
    "portfolio contact",
    "designer contact",
    "agency contact",
  ],
  fontFamily: ["DM Serif Display", "Inter"],
};
