export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-21.jpg",
  name: "landingfolio-hero-21",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "developer",
    "job board",
    "career",
    "newsletter",
    "email signup",
    "lead capture",
    "CTA",
    "call to action",
    "blog",
    "articles",
    "content cards",
    "SaaS",
    "purple accent",
    "violet",
    "clean design",
    "minimal",
    "modern",
    "professional",
    "tech",
    "startup",
    "concentric circles",
    "decorative",
    "email form",
    "subscription",
    "weekly articles",
    "community",
    "developers community",
    "dream job",
    "landingfolio",
    "clarity ui",
    "benefits list",
    "checkmarks",
    "article preview",
    "growth",
    "visual artist",
    "graphic design",
    "white background",
    "centered layout",
  ],
  fontFamily: ["Inter"],
};
