export const metadata = {
  imagePath: "agent-input/contact-form/beauty-with-intuition.jpg",
  name: "beauty-with-intuition",
  keywords: [
    "contact form",
    "appointment booking",
    "lash salon",
    "beauty salon",
    "spa",
    "booking form",
    "schedule appointment",
    "two column layout",
    "location info",
    "business hours",
    "radio buttons",
    "captcha",
    "elegant",
    "warm tones",
    "beige background",
    "terracotta",
    "brown",
    "serif font",
    "italic",
    "luxury",
    "beauty service",
    "skincare",
    "wellness",
    "esthetician",
    "contact section",
    "social media icons",
    "instagram",
    "pinterest",
    "form validation",
    "lead generation",
    "booking inquiry",
  ],
  fontFamily: ["Cormorant Garamond", "Inter"],
};
