export const metadata = {
  imagePath: "agent-input/feature-carousel/height.jpg",
  name: "height-feature-showcase",
  keywords: [
    "feature showcase",
    "product features",
    "task management",
    "project management",
    "workflow",
    "productivity",
    "SaaS landing",
    "app preview",
    "screenshot showcase",
    "feature list",
    "benefits section",
    "numbered section",
    "stacked cards",
    "Height app",
    "collaboration",
    "team chat",
    "custom workflows",
  ],
  fontFamily: ["Inter", "DM Serif Display"],
};
