export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-35.jpg",
  name: "landingfolio-hero-35",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "bakery",
    "bread",
    "artisan",
    "sourdough",
    "baking course",
    "food",
    "restaurant",
    "cafe",
    "cooking",
    "baking",
    "culinary",
    "course",
    "masterclass",
    "subscription",
    "monthly pricing",
    "dark theme",
    "black background",
    "split layout",
    "two column",
    "serif font",
    "italic",
    "elegant",
    "premium",
    "luxury",
    "CTA",
    "call to action",
    "watch trailer",
    "play button",
    "video",
    "navigation",
    "header",
    "minimal nav",
    "BakerStreet",
    "landingfolio",
    "food photography",
    "product hero",
    "sticky footer",
    "pricing bar",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
