export const metadata = {
  imagePath: "agent-input/contact-form/pano-cs-vip-roundtable.jpg",
  name: "pano-cs-vip-roundtable",
  keywords: [
    "contact form",
    "registration form",
    "VIP roundtable",
    "customer success",
    "event registration",
    "lead capture",
    "webinar signup",
    "discussion signup",
    "enterprise form",
    "B2B form",
    "dark theme",
    "green gradient",
    "neon green",
    "3D decorations",
    "tubes",
    "pipes",
    "futuristic design",
    "modern form",
    "centered layout",
    "card form",
    "SaaS signup",
    "event RSVP",
    "professional form",
    "corporate event",
    "roundtable discussion",
    "CS excellence",
    "customer success excellence",
    "secure spot",
    "form below",
    "italic headline",
    "serif accent",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
