export const metadata = {
  imagePath: "agent-input/contact-form/eigen-therapeutics.jpg",
  name: "eigen-therapeutics",
  keywords: [
    "contact form",
    "contact section",
    "dark theme",
    "dark mode",
    "biotech",
    "therapeutics",
    "healthcare",
    "pharmaceutical",
    "medical",
    "two column layout",
    "split layout",
    "form",
    "lead capture",
    "inquiry form",
    "message form",
    "social icons",
    "twitter",
    "linkedin",
    "facebook",
    "instagram",
    "address",
    "email contact",
    "recaptcha",
    "submit form",
    "minimal design",
    "modern form",
    "eigen therapeutics",
    "targeted therapies",
  ],
  fontFamily: ["Inter", "JetBrains Mono"],
};
