export const metadata = {
  imagePath: "agent-input/contact-form/i-am-superjuice.jpg",
  name: "i-am-superjuice",
  keywords: [
    "contact form",
    "contact",
    "form",
    "distributor",
    "business orders",
    "juice",
    "beverage",
    "food and drink",
    "organic",
    "natural",
    "gradient background",
    "sky blue",
    "beige",
    "cream",
    "rounded card",
    "radio buttons",
    "input fields",
    "submit button",
    "green button",
    "script font",
    "handwritten",
    "go with the flow",
    "phone number",
    "email address",
    "location",
    "netherlands",
    "superjuice",
    "distributor signup",
    "business inquiry",
    "partnership",
    "two column layout",
    "split layout",
    "light theme",
    "warm colors",
    "soft ui",
  ],
  fontFamily: ["Inter", "Allura"],
};
