export const metadata = {
  imagePath: "agent-input/contact-form/bausola-banch.jpg",
  name: "bausola-banch",
  keywords: [
    "contact form",
    "contact us",
    "contact",
    "form",
    "dark theme",
    "dark mode",
    "black background",
    "minimal",
    "minimalist",
    "clean design",
    "elegant",
    "workplace",
    "workbench",
    "furniture",
    "office",
    "industrial",
    "bausola",
    "two column",
    "split layout",
    "italic headline",
    "serif headline",
    "underline input",
    "border bottom input",
    "privacy policy",
    "gdpr",
    "checkbox",
    "message form",
    "email form",
    "landing page",
    "saas",
    "b2b",
    "corporate",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
