export const metadata = {
  imagePath: "agent-input/before-after/operate.jpg",
  name: "operate-before-after",
  keywords: [
    "before-after",
    "before after",
    "comparison",
    "chaos to clarity",
    "transformation",
    "scatter plot",
    "data visualization",
    "crm",
    "sales",
    "founders",
    "startup",
    "saas",
    "landing page",
    "hero section",
    "product showcase",
    "green theme",
    "sage green",
    "mint green",
    "nature palette",
    "organic",
    "early access",
    "alpha",
    "waitlist",
    "cta",
    "call to action",
    "animated",
    "dots pattern",
    "circles",
    "abstract",
    "minimal",
    "modern",
    "clean design",
    "card layout",
    "floating card",
    "product card",
    "feature highlight",
    "visual metaphor",
    "organize",
    "organization",
    "productivity",
    "workflow",
  ],
  fontFamily: ["Inter"],
};
