export const metadata = {
  imagePath: "agent-input/biography/smith-robinson.jpg",
  name: "smith-robinson",
  keywords: [
    "biography",
    "origin story",
    "about us",
    "company story",
    "founding story",
    "team history",
    "client logos",
    "client showcase",
    "trusted by",
    "dark theme",
    "navy background",
    "gold accent",
    "yellow accent",
    "pixel art",
    "retro gaming",
    "adventure game",
    "creative agency",
    "design studio",
    "handwritten annotations",
    "dashed border",
    "serif title",
    "italic heading",
    "underlined text",
    "PBS",
    "Cartoon Network",
    "New York Times",
    "multimedia",
    "director",
    "designer",
    "emmy winning",
    "two column layout",
    "storytelling",
    "brand story",
    "company history",
    "founders story",
    "creative philosophy",
    "humor",
    "playful",
    "professional",
  ],
  fontFamily: ["Playfair Display", "Inter", "Handlee"],
};
