export const metadata = {
  imagePath: "agent-input/contact-form/new-valley-labs.jpg",
  name: "new-valley-labs",
  keywords: [
    "contact form",
    "contact us",
    "form",
    "contact section",
    "retro",
    "vintage",
    "70s style",
    "playful",
    "quirky",
    "fun",
    "creative",
    "illustration",
    "character",
    "mascot",
    "flower character",
    "beige",
    "cream background",
    "orange",
    "teal",
    "pink",
    "newsletter",
    "subscribe",
    "email",
    "name input",
    "pronouns",
    "pitch deck",
    "feedback",
    "inquiry",
    "let's chat",
    "submit button",
    "checkbox",
    "startup",
    "creative agency",
    "design studio",
  ],
  fontFamily: ["DM Sans", "Inter"],
};
