export const metadata = {
  imagePath: "agent-input/contact-form/hyve-systems.jpg",
  name: "hyve-systems",
  keywords: [
    "contact form",
    "discovery call",
    "AI business",
    "consultation",
    "calendly",
    "sales contact",
    "booking form",
    "lead generation",
    "business inquiry",
    "get in touch",
    "green",
    "teal",
    "serif heading",
    "italic",
    "two column",
    "cta section",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
