export const metadata = {
  imagePath: "agent-input/testimonial-tweets/print-for-figma.jpg",
  name: "print-for-figma-testimonial",
  keywords: [
    "testimonial",
    "testimonials",
    "review",
    "reviews",
    "social proof",
    "feedback",
    "customer reviews",
    "user feedback",
    "light theme",
    "light mode",
    "white background",
    "off-white",
    "figma",
    "print",
    "design tool",
    "plugin",
    "5 stars",
    "five stars",
    "star rating",
    "rating",
    "quote",
    "quote marks",
    "quotation",
    "centered",
    "center aligned",
    "minimal",
    "minimalist",
    "clean design",
    "simple",
    "call to action",
    "cta button",
    "view all reviews",
    "testimonial card",
    "endorsement",
    "recommendation",
    "product review",
    "app review",
    "featured review",
    "highlight review",
    "single testimonial",
    "hero testimonial",
    "purple accent",
    "yellow stars",
    "gold stars",
  ],
  fontFamily: ["Inter"],
};
