export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-33.jpg",
  name: "landingfolio-hero-33",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "bakery",
    "bread making",
    "bread",
    "artisan",
    "baking",
    "food",
    "culinary",
    "cooking course",
    "dark theme",
    "dark mode",
    "circular images",
    "round images",
    "image gallery",
    "asymmetric layout",
    "CTA",
    "call to action",
    "video trailer",
    "watch video",
    "navigation",
    "header",
    "subscription",
    "monthly price",
    "pricing",
    "serif font",
    "italic headline",
    "elegant",
    "premium",
    "wheat",
    "flour",
    "dough",
    "kneading",
    "sourdough",
    "artisan bread",
    "bakery website",
    "cooking class",
    "masterclass",
    "tutorial",
    "learn",
    "course",
    "landingfolio",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
