export const metadata = {
  imagePath: "agent-input/testimonial-tweets/prototyper-for-figma.jpg",
  name: "prototyper-for-figma-testimonial",
  keywords: [
    "testimonial",
    "testimonials",
    "tweets",
    "twitter",
    "x",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "dark theme",
    "dark mode",
    "gray background",
    "card grid",
    "2x2 grid",
    "avatar",
    "profile",
    "handle",
    "username",
    "designer",
    "product designer",
    "interaction designer",
    "figma",
    "prototyper",
    "framer",
    "design tool",
    "plugin",
    "what designers are saying",
    "social media",
    "endorsement",
    "recommendation",
    "tweet card",
    "twitter actions",
    "like",
    "retweet",
    "comment",
  ],
  fontFamily: ["Inter"],
};
