export const metadata = {
  imagePath: "agent-input/biography/designing-in-figma-book.jpg",
  name: "designing-in-figma-book",
  keywords: [
    "biography",
    "bio",
    "profile",
    "personal",
    "about me",
    "about",
    "author",
    "book",
    "ebook",
    "figma",
    "design",
    "designer",
    "newsletter",
    "introduction",
    "colorful",
    "playful",
    "friendly",
    "light theme",
    "white background",
    "card",
    "abstract shapes",
    "decorative",
    "organic shapes",
    "bullet list",
    "features",
    "learning",
    "education",
    "course",
    "guide",
    "tips",
    "recommendations",
    "research",
    "table of contents",
    "vector networks",
    "components",
    "styles",
    "auto layout",
    "resizable layouts",
    "export",
    "svg",
    "design tools",
    "ui design",
    "product design",
    "wave emoji",
    "greeting",
    "hello",
    "eugene",
    "clean design",
    "modern",
    "creative",
    "purple accent",
    "coral",
    "sky blue",
    "yellow",
    "pastel colors",
  ],
  fontFamily: ["Inter"],
};
