export const metadata = {
  imagePath: "agent-input/contact-form/jeff-wall.jpg",
  name: "jeff-wall",
  keywords: [
    "contact form",
    "contact",
    "form",
    "dark theme",
    "dark background",
    "purple",
    "violet",
    "gold",
    "yellow",
    "serif",
    "italic",
    "elegant",
    "luxury",
    "premium",
    "send message",
    "name",
    "email",
    "message",
    "textarea",
    "input fields",
    "gradient background",
    "deep purple",
    "dark purple",
    "contact section",
    "contact us",
    "get in touch",
    "reach out",
    "inquiry",
    "feedback",
    "support",
    "customer support",
    "landing page",
    "modern",
    "minimal",
    "clean",
    "professional",
    "business",
    "agency",
    "portfolio",
    "creative",
  ],
  fontFamily: ["Playfair Display", "Inter"],
};
