export const metadata = {
  imagePath: "agent-input/testimonial-tweets/webflow-conf-2022.jpg",
  name: "webflow-conf-2022",
  keywords: [
    "testimonial",
    "testimonials",
    "twitter",
    "tweets",
    "social proof",
    "event",
    "conference",
    "webflow",
    "nocodeconf",
    "attendee feedback",
    "quote cards",
    "dark theme",
    "black background",
    "three column",
    "grid layout",
    "decorative squares",
    "geometric accents",
    "yellow accent",
    "pink accent",
    "white accent",
    "revolution quote",
    "social media",
    "x twitter",
    "event testimonials",
    "conference feedback",
    "user quotes",
    "past attendees",
    "landing page",
    "marketing",
    "saas",
  ],
  fontFamily: ["Inter"],
};
