export const metadata = {
  imagePath: "agent-input/testimonial-slider/jords-and-co.jpg",
  name: "jords-and-co-testimonial-slider",
  keywords: [
    "testimonial",
    "testimonials",
    "slider",
    "carousel",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "quotes",
    "quote card",
    "light theme",
    "light background",
    "gray theme",
    "purple accent",
    "centered layout",
    "serif font",
    "italic headline",
    "product thumbnail",
    "company logo",
    "avatar",
    "author info",
    "pagination dots",
    "landing page",
    "saas",
    "startup",
    "marketing",
    "waitlist",
    "signups",
    "founders",
    "real results",
    "proof",
    "marco",
    "jords and co",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
