export const metadata = {
  imagePath: "agent-input/biography/derek-orr.jpg",
  name: "derek-orr",
  keywords: [
    "biography",
    "bio",
    "about",
    "about me",
    "personal website",
    "portfolio",
    "designer",
    "UX designer",
    "product designer",
    "creative",
    "profile",
    "introduction",
    "personal branding",
    "career",
    "resume",
    "CV",
    "signature",
    "handwritten signature",
    "three column",
    "multi column text",
    "serif headline",
    "italic headline",
    "professional",
    "minimal",
    "clean",
    "white background",
    "light theme",
    "freelancer",
    "consultant",
    "Derek Orr",
    "career break",
    "dad",
    "neurodivergent",
    "LinkedIn",
    "download CV",
    "profile photo",
    "circular avatar",
    "personal statement",
    "work history",
    "experience",
    "Airbnb",
    "Uber",
    "Instagram",
    "eBay",
    "Duolingo",
    "HCI",
    "master degree",
  ],
  fontFamily: ["Playfair Display", "Inter"],
};
