export const metadata = {
  imagePath: "agent-input/testimonial-tweets/intro-to-icons-by-mds.jpg",
  name: "intro-to-icons-by-mds",
  keywords: [
    "testimonial",
    "twitter",
    "tweets",
    "social proof",
    "reviews",
    "customer feedback",
    "icon design",
    "course",
    "mds",
    "grid layout",
    "cards",
    "user quotes",
    "x",
    "social media",
    "education",
    "design course",
    "intro to icons",
  ],
  fontFamily: ["Inter"],
};
