export const metadata = {
  imagePath: "agent-input/contact-form/hedera-dx.jpg",
  name: "hedera-dx",
  keywords: [
    "contact form",
    "contact us",
    "form",
    "biotech",
    "healthcare",
    "medical",
    "pharmaceutical",
    "liquid biopsy",
    "diagnostics",
    "enterprise",
    "B2B",
    "business inquiry",
    "lead generation",
    "split layout",
    "two column",
    "company info",
    "address",
    "social links",
    "twitter",
    "linkedin",
    "checkbox",
    "consent",
    "GDPR",
    "privacy",
    "dropdown",
    "select",
    "message",
    "textarea",
    "clean design",
    "minimal",
    "white background",
    "purple accent",
    "professional",
    "corporate",
    "Switzerland",
    "Hedera Dx",
  ],
  fontFamily: ["Inter"],
};
