export const metadata = {
  imagePath: "/Users/choesumin/Desktop/dev/choisumin/landing-mon-components/agent-input/landingfolio-stats/stats-7.jpg",
  name: "stats-7",
  keywords: [
    "stats",
    "statistics",
    "metrics",
    "numbers",
    "count",
    "data",
    "dashboard",
    "430k",
    "customers",
    "subscribers",
    "transaction",
    "revenue",
    "card",
    "grid",
    "three column",
    "icon stats",
    "active customers",
    "email subscribers",
    "monthly transaction",
    "business metrics",
    "key performance",
    "kpi",
    "saas metrics",
    "growth",
    "user count",
    "subscriber count",
    "money",
    "investment",
    "light theme",
    "white background",
    "gray cards",
    "rounded cards",
    "minimal",
    "clean design",
    "landing page",
    "marketing",
    "startup",
    "rareblocks",
    "developer",
    "dev life",
    "solutions",
  ],
  fontFamily: ["Inter"],
};
