export const metadata = {
  imagePath: "agent-input/contact-form/venture-climate-alliance.jpg",
  name: "venture-climate-alliance",
  keywords: [
    "contact form",
    "membership form",
    "sign up",
    "join us",
    "alliance",
    "venture capital",
    "investor",
    "climate",
    "sustainability",
    "VCA",
    "two column layout",
    "split layout",
    "lavender",
    "purple background",
    "light theme",
    "minimal form",
    "clean design",
    "professional",
    "enterprise",
    "B2B",
    "membership",
    "application form",
    "simple form",
    "lead capture",
    "venture investor",
    "global membership",
  ],
  fontFamily: ["Inter"],
};
