export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-36.jpg",
  name: "landingfolio-hero-36",
  keywords: [
    "hero",
    "landing page",
    "newsletter",
    "email signup",
    "email subscription",
    "marketing",
    "weekly newsletter",
    "purple background",
    "violet theme",
    "blue gradient",
    "email form",
    "input fields",
    "subscribe form",
    "featured logos",
    "brand logos",
    "trust badges",
    "social proof",
    "avatar group",
    "user avatars",
    "marketers",
    "SaaS",
    "startup",
    "CTA",
    "call to action",
    "navigation header",
    "white nav",
    "rounded card",
    "italic headline",
    "serif heading",
    "modern design",
    "two column",
    "split layout",
  ],
  fontFamily: ["DM Serif Display", "Inter"],
};
