export const metadata = {
  imagePath: "agent-input/biography/block-themes-pro-course.jpg",
  name: "block-themes-pro-course",
  keywords: [
    "biography",
    "bio",
    "profile",
    "instructor",
    "meet the instructor",
    "course",
    "online course",
    "about section",
    "about me",
    "teacher",
    "educator",
    "wordpress",
    "block themes",
    "gutenberg",
    "web design",
    "web development",
    "website builder",
    "developer",
    "designer",
    "light theme",
    "white background",
    "clean design",
    "minimal",
    "minimalist",
    "two column",
    "profile image",
    "circular avatar",
    "round avatar",
    "blue accent",
    "purple accent",
    "indigo accent",
    "sans-serif",
    "introduction",
    "professional",
    "personal",
    "landing page",
    "sales page",
    "product page",
    "course landing",
    "education",
    "learning",
    "tutorial",
    "training",
    "squarespace",
    "shopify",
    "divi",
    "site editor",
    "brad hogan",
  ],
  fontFamily: ["Inter"],
};
