export const metadata = {
  imagePath: "agent-input/biography/typography-layout-course.jpg",
  name: "typography-layout-course",
  keywords: [
    "about me",
    "biography",
    "bio section",
    "introduction",
    "meet the designer",
    "designer bio",
    "creator bio",
    "course creator",
    "masterclass",
    "typography course",
    "layout course",
    "design course",
    "online course",
    "digital product",
    "two column",
    "side by side",
    "portrait",
    "headshot",
    "profile photo",
    "podcast microphone",
    "dark theme",
    "black background",
    "client logos",
    "agency logos",
    "brand logos",
    "logo strip",
    "trusted by",
    "worked with",
    "clients and agencies",
    "AKQA",
    "Nike",
    "Hennessy",
    "italic heading",
    "bold heading",
    "large typography",
    "section number",
    "minimal design",
    "professional",
    "creative professional",
    "award winning designer",
    "experience",
    "credentials",
    "landing page",
    "course landing",
    "sales page",
    "about section",
  ],
  fontFamily: ["Inter"],
};
