export const metadata = {
  imagePath: "agent-input/testimonial-slider/anesh-kangutkar.jpg",
  name: "anesh-kangutkar-testimonial",
  keywords: [
    "testimonial",
    "testimonials",
    "slider",
    "carousel",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "quotes",
    "dark theme",
    "black background",
    "burnt orange",
    "terracotta",
    "two column",
    "split layout",
    "italic headline",
    "company list",
    "navigation arrows",
    "profile card",
    "author info",
    "landing page",
    "portfolio",
    "freelancer",
    "designer testimonial",
    "client feedback",
    "professional",
    "minimal",
    "anesh kangutkar",
  ],
  fontFamily: ["Inter"],
};
