export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-3.jpg",
  name: "landingfolio-hero-3",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "developer",
    "recruitment",
    "job platform",
    "hiring",
    "employers",
    "talent search",
    "developer search",
    "tech hiring",
    "search bar",
    "find developer",
    "dark theme",
    "black background",
    "profile cards",
    "testimonials",
    "trust badges",
    "ratings",
    "reviews",
    "cyan accent",
    "gradient",
    "connecting",
    "job matching",
    "SaaS",
    "platform",
    "call to action",
    "CTA",
    "navigation",
    "modern design",
    "DuskUI",
  ],
  fontFamily: ["Inter"],
};
