export const metadata = {
  imagePath: "agent-input/contact-form/oovra.jpg",
  name: "oovra-contact-form",
  keywords: [
    "contact form",
    "schedule meeting",
    "meeting form",
    "appointment form",
    "lead capture",
    "business inquiry",
    "cream background",
    "beige theme",
    "light theme",
    "warm colors",
    "two column layout",
    "minimal design",
    "clean form",
    "elegant form",
    "professional form",
    "schedule a meeting",
    "italic serif headline",
    "input fields",
    "first name last name",
    "email form",
    "instagram field",
    "message textarea",
    "contact us",
    "inquiry form",
    "oovra",
    "off-white background",
    "subtle design",
    "vertical divider",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
