export const metadata = {
  imagePath: "agent-input/beautiful-sections/rysa-how-it-works.png",
  name: "rysa-how-it-works",
  keywords: [
    "how-it-works",
    "steps",
    "process",
    "tutorial",
    "onboarding",
    "fashion",
    "wardrobe",
    "stylist",
    "app-showcase",
    "features",
    "grid",
    "cards",
    "saas",
    "mobile-app",
    "landing-page",
    "cta",
    "minimal",
    "clean",
    "modern",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
