export const metadata = {
  imagePath: "agent-input/biography/gal-shir.jpg",
  name: "gal-shir",
  keywords: [
    "biography",
    "bio",
    "profile",
    "personal",
    "about me",
    "about",
    "portfolio",
    "designer",
    "brand designer",
    "independent",
    "freelancer",
    "minimal",
    "minimalist",
    "light theme",
    "white background",
    "contact",
    "email",
    "location",
    "tel aviv",
    "israel",
    "two column",
    "profile image",
    "avatar",
    "circular photo",
    "round photo",
    "read more",
    "clean design",
    "simple layout",
    "personal website",
    "landing page",
    "introduction",
    "professional",
    "creative",
    "visual identity",
    "logo design",
    "branding",
    "art direction",
    "illustration",
    "startup",
    "lets chat",
    "contact section",
    "about section",
    "map pin",
    "location icon",
  ],
  fontFamily: ["Inter"],
};
