export const metadata = {
  imagePath: "agent-input/beautiful-sections/60-logo-tips-author.png",
  name: "logo-tips-author",
  keywords: [
    "author",
    "author section",
    "about author",
    "bio",
    "biography",
    "book author",
    "ebook",
    "logo design",
    "brand design",
    "designer",
    "specialist",
    "profile",
    "profile section",
    "avatar",
    "circular avatar",
    "heart icon",
    "dashed heart",
    "testimonial",
    "about me",
    "credentials",
    "experience",
    "15 years",
    "career",
    "guide",
    "book",
    "light gray",
    "minimal",
    "clean design",
    "centered layout",
    "serif font",
    "gal shir",
    "logo tips",
    "design book",
    "hands-on guide",
    "step-by-step",
  ],
  fontFamily: ["DM Serif Display", "Inter"],
};
