export const metadata = {
  imagePath: "agent-input/before-after/design-buddy.jpg",
  name: "design-buddy-before-after",
  keywords: [
    "before after",
    "comparison",
    "before and after",
    "design feedback",
    "design review",
    "design audit",
    "ui feedback",
    "ux review",
    "accessibility score",
    "layout score",
    "typography score",
    "color score",
    "design score",
    "rating",
    "score card",
    "progress indicator",
    "circular progress",
    "ring progress",
    "onboarding flow",
    "contractor onboarding",
    "milestone tracker",
    "step progress",
    "stepper",
    "checklist",
    "task completion",
    "workflow steps",
    "light theme",
    "white background",
    "gray background",
    "two column",
    "vertical stack",
    "card layout",
    "feedback card",
    "ai feedback",
    "design analysis",
    "design improvement",
    "saas",
    "landing page",
    "feature section",
    "value proposition",
    "teal accent",
    "green accent",
    "progress bar",
  ],
  fontFamily: ["Inter"],
};
