export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-15.jpg",
  name: "landingfolio-hero-15",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "remote work",
    "productivity",
    "SaaS",
    "email signup",
    "newsletter",
    "lead capture",
    "CTA",
    "call to action",
    "split layout",
    "two column",
    "image hero",
    "photo hero",
    "professional",
    "workspace",
    "work from home",
    "WFH",
    "free trial",
    "postcrafts",
    "landingfolio",
    "orange accent",
    "cream background",
    "warm colors",
    "curved text",
    "circular badge",
    "email form",
    "statistics",
    "social proof",
    "decorative lines",
    "modern",
    "clean design",
    "B2B",
    "startup",
    "collaboration",
    "desk organization",
  ],
  fontFamily: ["Inter"],
};
