export const metadata = {
  imagePath: "agent-input/testimonial-tweets/convert-kit-newsletter-plan.jpg",
  name: "convert-kit-newsletter-plan",
  keywords: [
    "testimonial",
    "testimonials",
    "twitter",
    "tweets",
    "x",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "quotes",
    "light theme",
    "white background",
    "card layout",
    "horizontal layout",
    "multi-card",
    "avatar",
    "profile picture",
    "convertkit",
    "newsletter",
    "email marketing",
    "creators",
    "creator economy",
    "social media",
    "twitter testimonial",
    "tweet card",
    "mention",
    "handle",
    "username",
    "progress bar",
    "slider indicator",
    "teal accent",
    "clean design",
    "minimal",
    "professional",
    "saas",
    "marketing",
    "landing page",
    "trust signals",
  ],
  fontFamily: ["Inter"],
};
