export const metadata = {
  imagePath: "agent-input/landingfolio-stats/stats-17.jpg",
  name: "stats-17",
  keywords: [
    "stats",
    "statistics",
    "numbers",
    "metrics",
    "facts",
    "dark theme",
    "dark background",
    "black background",
    "glow effect",
    "light effect",
    "blue glow",
    "three columns",
    "grid layout",
    "card container",
    "rounded container",
    "border",
    "divider",
    "vertical divider",
    "tickets",
    "customers",
    "satisfaction rate",
    "percentage",
    "serif title",
    "modern",
    "professional",
    "landing page",
    "section",
    "dark mode",
    "glassmorphism",
  ],
  fontFamily: ["Inter", "Instrument Serif"],
};
