export const metadata = {
  imagePath: "agent-input/biography/serge-tiutyk.jpg",
  name: "serge-tiutyk-biography",
  keywords: [
    "biography",
    "about",
    "about section",
    "about me",
    "personal bio",
    "designer bio",
    "portfolio",
    "profile",
    "introduction",
    "polaroid",
    "photo frame",
    "photo gallery",
    "photo slider",
    "pagination dots",
    "watermark text",
    "light theme",
    "white background",
    "minimal",
    "clean design",
    "two column",
    "split layout",
    "personal branding",
    "freelancer",
    "UI/UX designer",
    "digital designer",
    "career story",
    "professional profile",
    "contact section",
    "rotated photo",
    "tilted image",
    "elegant",
    "modern portfolio",
    "serge tiutyk",
  ],
  fontFamily: ["Inter"],
};
