export const metadata = {
  imagePath: "agent-input/feature-carousel/modulify.jpg",
  name: "website-template-carousel",
  keywords: [
    "website templates",
    "template carousel",
    "website designs",
    "multipurpose",
    "saas website",
    "portfolio",
    "creative agency",
    "restaurant",
    "architecture",
    "consulting",
    "construction",
    "ai website builder",
    "web design showcase",
    "template gallery",
    "carousel slider",
    "category navigation",
    "website preview",
    "template selector",
    "design showcase",
    "landing page templates",
  ],
  fontFamily: ["Inter"],
};
