export const metadata = {
  imagePath: "agent-input/testimonial-tweets/helo.jpg",
  name: "helo-testimonial-tweets",
  keywords: [
    "testimonial",
    "twitter",
    "tweets",
    "social proof",
    "reviews",
    "customer feedback",
    "helo",
    "grid",
    "cards",
    "user quotes",
    "x",
    "social media",
    "lavender background",
    "light theme",
    "quote marks",
    "scattered layout",
    "masonry",
    "bento",
    "paper airplane",
  ],
  fontFamily: ["Inter"],
};
