export const metadata = {
  imagePath: "agent-input/feature-carousel/echo.jpg",
  name: "feature-accordion-code-editor",
  keywords: [
    "feature",
    "accordion",
    "code editor",
    "workflow",
    "drag and drop",
    "developer tools",
    "IDE",
    "productivity",
    "coding",
    "workspace",
    "team management",
    "snippet",
    "echo",
    "landing page",
    "two column layout",
    "expandable",
    "collapsible",
  ],
  fontFamily: ["Inter"],
};
