export const metadata = {
  imagePath: "agent-input/contact-form/bauplan.jpg",
  name: "bauplan",
  keywords: [
    "contact form",
    "alpha signup",
    "private alpha",
    "waitlist",
    "lead capture",
    "email capture",
    "form",
    "signup form",
    "registration",
    "early access",
    "beta signup",
    "startup",
    "SaaS",
    "developer tools",
    "linkedin",
    "github",
    "social links",
    "minimalist design",
    "clean form",
    "card form",
    "centered form",
    "gradient button",
    "blue button",
    "heart icon",
    "abstract background",
    "illustration background",
    "landscape art",
    "modern design",
    "light theme",
    "bauplan",
  ],
  fontFamily: ["Inter"],
};
