export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-24.jpg",
  name: "landingfolio-hero-24",
  keywords: [
    "hero",
    "office accessories",
    "e-commerce",
    "search",
    "landing page",
    "dark overlay",
    "statistics",
    "product search",
    "online store",
    "retail",
    "shopping",
    "office supplies",
    "modern",
    "professional",
  ],
  fontFamily: ["Inter", "Instrument Serif"],
};
