export const metadata = {
  imagePath: "agent-input/feature-carousel/aerotime.jpg",
  name: "task-management-feature",
  keywords: [
    "task management",
    "productivity",
    "feature section",
    "task capture",
    "scheduling",
    "collaboration",
    "saas landing",
    "two column layout",
    "feature list",
    "onboarding",
    "duration slider",
    "time picker",
    "aerotime",
    "centralize tasks",
    "prioritize",
  ],
  fontFamily: ["Inter"],
};
