export const metadata = {
  imagePath: "agent-input/biography/matt-rothenberg.jpg",
  name: "matt-rothenberg",
  keywords: [
    "biography",
    "bio",
    "profile",
    "personal",
    "about me",
    "portfolio",
    "developer",
    "designer",
    "monospace",
    "typewriter",
    "minimal",
    "minimalist",
    "light theme",
    "white background",
    "work experience",
    "career",
    "resume",
    "cv",
    "personal website",
    "landing page",
    "introduction",
    "professional",
    "tech",
    "engineer",
    "software developer",
    "new york",
    "replicate",
    "github",
    "copilot",
    "clearbit",
    "heroku",
    "undp",
    "employable",
    "italic text",
    "underline links",
    "serif-free",
    "clean design",
    "simple layout",
    "two column",
    "profile image",
    "grayscale photo",
  ],
  fontFamily: ["JetBrains Mono"],
};
