export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-29.jpg",
  name: "landingfolio-hero-29",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "bakery",
    "bread",
    "artisan",
    "bread making",
    "food",
    "restaurant",
    "cafe",
    "cooking",
    "baking",
    "culinary",
    "course",
    "masterclass",
    "tutorial",
    "video",
    "trailer",
    "watch video",
    "full screen background",
    "background image",
    "dark theme",
    "overlay",
    "centered content",
    "serif font",
    "italic",
    "elegant",
    "rustic",
    "warm",
    "organic",
    "natural",
    "CTA",
    "call to action",
    "two buttons",
    "play button",
    "scroll down",
    "navigation",
    "header",
    "minimal nav",
    "landingfolio",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
