export const metadata = {
  imagePath: "agent-input/before-after/makeover-studio.jpg",
  name: "makeover-studio",
  keywords: [
    "before after",
    "before and after",
    "comparison",
    "makeover",
    "transformation",
    "website redesign",
    "branding",
    "browser mockup",
    "product showcase",
    "furniture",
    "sofa",
    "landing page",
    "tab selector",
    "toggle",
    "warm tones",
    "beige",
    "taupe",
    "neutral colors",
    "minimal design",
    "clean layout",
    "quality showcase",
    "website template",
    "design agency",
    "portfolio",
    "case study",
    "interactive demo",
    "preview card",
    "light theme",
    "soft background",
  ],
  fontFamily: ["Inter"],
};
