export const metadata = {
  imagePath: "agent-input/feature-carousel/copilot.jpg",
  name: "finance-feature-showcase",
  keywords: [
    "finance",
    "banking",
    "fintech",
    "feature showcase",
    "tabs",
    "spending tracker",
    "budget",
    "savings",
    "net worth",
    "investments",
    "transactions",
    "bank integration",
    "financial dashboard",
    "money management",
    "personal finance",
    "copilot",
    "dark theme",
    "feature section",
    "tabbed interface",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
