export const metadata = {
  imagePath: "agent-input/biography/webflix-studio.jpg",
  name: "webflix-studio",
  keywords: [
    "biography",
    "bio",
    "about",
    "about me",
    "about section",
    "personal introduction",
    "founder bio",
    "founder story",
    "studio introduction",
    "agency about",
    "webflow",
    "webflow studio",
    "web design agency",
    "freelancer",
    "designer",
    "developer",
    "lead designer",
    "personal branding",
    "dark theme",
    "dark mode",
    "dark background",
    "minimal",
    "clean design",
    "professional",
    "modern",
    "teal accent",
    "cyan accent",
    "avatar",
    "profile photo",
    "circular avatar",
    "avatar border",
    "pill badge",
    "badge label",
    "multi paragraph",
    "long form text",
    "personal letter",
    "casual tone",
    "friendly introduction",
    "founder message",
    "marketing team",
    "tech company",
    "startup",
    "webflow expert",
    "agency",
    "studio",
    "Felix Meens",
    "curved section",
    "wave section",
    "gradient background",
  ],
  fontFamily: ["Inter"],
};
