export const metadata = {
  imagePath: "agent-input/biography/ensage.jpg",
  name: "ensage",
  keywords: [
    "biography",
    "about",
    "about section",
    "personal",
    "profile",
    "designer",
    "developer",
    "freelancer",
    "agency",
    "boutique",
    "solo founder",
    "founder story",
    "experience",
    "expertise",
    "years of experience",
    "old school",
    "veteran",
    "two column layout",
    "split layout",
    "dark theme",
    "teal",
    "dark teal",
    "serif font",
    "elegant",
    "professional",
    "consulting",
    "portfolio",
    "personal brand",
    "branding",
    "UX/UI",
    "product design",
    "digital design",
    "ensage",
    "zlatko",
    "thoughtful",
    "meticulous",
    "collaborative",
    "direct collaboration",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
