export const metadata = {
  imagePath: "agent-input/beautiful-sections/rysa-features.png",
  name: "rysa-features",
  keywords: [
    "features",
    "feature-grid",
    "bento",
    "bento-grid",
    "wardrobe",
    "fashion",
    "styling",
    "ai-stylist",
    "dashboard",
    "saas",
    "product-features",
    "cards",
    "grid-layout",
    "clean",
    "minimal",
    "modern",
    "white",
    "light-theme",
    "cta",
    "call-to-action",
  ],
  fontFamily: ["Inter"],
};
