export const metadata = {
  imagePath: "agent-input/biography/feel-good-productivity.jpg",
  name: "feel-good-productivity",
  keywords: [
    "about the author",
    "author bio",
    "author biography",
    "book author",
    "writer",
    "author section",
    "about section",
    "bio",
    "biography",
    "personal",
    "light theme",
    "white card",
    "clean design",
    "minimal",
    "minimalist",
    "elegant",
    "serif font",
    "lora font",
    "italic",
    "brown accent",
    "terracotta",
    "warm color",
    "book icon",
    "centered layout",
    "center aligned",
    "author photo",
    "portrait",
    "profile image",
    "rounded image",
    "card layout",
    "text block",
    "paragraphs",
    "reading",
    "publishing",
    "book landing",
    "book website",
    "productivity",
    "self help",
    "non-fiction",
    "ali abdaal",
    "feel good productivity",
    "doctor",
    "entrepreneur",
    "youtuber",
    "content creator",
    "modern",
    "professional",
    "soft shadows",
    "light background",
    "gray background",
    "off-white",
  ],
  fontFamily: ["Lora", "Source Sans 3"],
};
