export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-2.jpg",
  name: "landingfolio-hero-2",
  keywords: [
    "hero",
    "landing page",
    "education",
    "learning platform",
    "social media",
    "mentorship",
    "online courses",
    "professionals",
    "career growth",
    "light theme",
    "white background",
    "collage layout",
    "statistics cards",
    "photo grid",
    "colorful shapes",
    "geometric design",
    "signup",
    "CTA",
    "call to action",
    "navigation header",
    "yellow accent",
    "blue accent",
    "purple accent",
    "green accent",
    "serif headline",
    "modern design",
    "SaaS",
    "startup",
  ],
  fontFamily: ["Inter"],
};
