export const metadata = {
  imagePath: "agent-input/lead-capture-hero/midday.jpg",
  name: "midday-hero",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "lead capture",
    "email capture",
    "waitlist",
    "financial",
    "fintech",
    "SaaS",
    "business",
    "finance OS",
    "accounting",
    "bookkeeping",
    "AI-powered",
    "open source",
    "time tracking",
    "receipt linking",
    "profit loss",
    "vault",
    "feature icons",
    "minimal design",
    "light theme",
    "cream background",
    "centered layout",
    "call to action",
    "CTA",
    "email input",
    "join waitlist",
    "midday",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
