export const metadata = {
  imagePath: "agent-input/contact-form/eight-pixel.jpg",
  name: "eight-pixel",
  keywords: [
    "contact form",
    "contact us",
    "partnership",
    "growth",
    "booking",
    "book a call",
    "lead capture",
    "form",
    "name input",
    "email input",
    "message textarea",
    "send message",
    "CTA",
    "call to action",
    "blue background",
    "bold color",
    "profile picture",
    "avatar",
    "testimonial style",
    "two column",
    "split layout",
    "agency",
    "business partnership",
    "consulting",
    "italic headline",
    "serif headline",
    "underline inputs",
    "minimal form",
    "professional",
  ],
  fontFamily: ["Inter"],
};
