export const metadata = {
  imagePath: "agent-input/biography/stephanie-bruce.jpg",
  name: "stephanie-bruce",
  keywords: [
    "biography",
    "about me",
    "personal website",
    "portfolio",
    "web designer",
    "freelancer",
    "creative",
    "dark theme",
    "photo gallery",
    "tilted photos",
    "overlapping images",
    "italic headline",
    "minimalist",
    "professional",
    "developer",
    "webflow",
    "framer",
    "personal branding",
    "introduction",
    "about section",
    "creative portfolio",
    "designer bio",
    "two column layout",
    "photo collage",
  ],
  fontFamily: ["DM Sans"],
};
