export const metadata = {
  imagePath: "agent-input/contact-form/deeo.jpg",
  name: "deeo",
  keywords: [
    "contact form",
    "contact section",
    "get in touch",
    "collaboration",
    "agency",
    "studio",
    "dark theme",
    "dark mode",
    "black background",
    "minimal",
    "elegant",
    "serif font",
    "italic heading",
    "form fields",
    "name input",
    "email input",
    "company input",
    "budget dropdown",
    "timeline",
    "submit button",
    "email link",
    "business inquiry",
    "project inquiry",
    "deeo",
    "creative studio",
    "design agency",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
