export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-20.jpg",
  name: "landingfolio-hero-20",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "team",
    "communication",
    "collaboration",
    "SaaS",
    "UI kit",
    "component library",
    "website builder",
    "professional",
    "team members",
    "user avatars",
    "profile cards",
    "floating cards",
    "online status",
    "video intro",
    "free trial",
    "CTA",
    "call to action",
    "centered layout",
    "clarity UI",
    "blue accent",
    "white background",
    "clean design",
    "modern",
    "B2B",
    "startup",
    "remote team",
    "product team",
    "designer",
    "developer",
    "account manager",
    "navigation header",
    "colorful avatars",
    "circular photos",
    "user profiles",
    "blocks",
    "components",
  ],
  fontFamily: ["Inter"],
};
