export const metadata = {
  imagePath: "agent-input/biography/full-stack-ui.jpg",
  name: "full-stack-ui",
  keywords: [
    "biography",
    "bio",
    "about",
    "about me",
    "profile",
    "introduction",
    "personal",
    "designer",
    "developer",
    "full stack",
    "fullstack",
    "freelancer",
    "hero",
    "landing",
    "two column",
    "split layout",
    "light theme",
    "light blue background",
    "pastel",
    "soft",
    "clean",
    "minimal",
    "minimalist",
    "professional",
    "portfolio",
    "personal website",
    "contact",
    "email",
    "finland",
    "nordic",
    "teaching",
    "instructor",
    "course creator",
    "design development",
    "portrait",
    "headshot",
    "profile photo",
  ],
  fontFamily: ["Inter"],
};
