export const metadata = {
  imagePath: "agent-input/contact-form/hunter-hastings.jpg",
  name: "hunter-hastings",
  keywords: [
    "contact",
    "contact form",
    "contact page",
    "form",
    "dark theme",
    "dark mode",
    "email",
    "linkedin",
    "twitter",
    "dribbble",
    "social links",
    "social media",
    "get in touch",
    "reach out",
    "message form",
    "inquiry",
    "building",
    "project inquiry",
    "budget",
    "timeframe",
    "collaboration",
    "hire",
    "freelance",
    "designer contact",
    "glow effect",
    "gradient glow",
    "blue glow",
    "yellow glow",
    "minimal",
    "modern",
    "clean",
    "elegant",
    "send message",
    "name input",
    "email input",
    "textarea",
    "serif heading",
    "italic text",
    "portfolio",
    "personal website",
    "designer",
    "developer",
    "creative",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
