export const metadata = {
  imagePath: "agent-input/testimonial-tweets/userconf-2014.jpg",
  name: "userconf-2014",
  keywords: [
    "testimonial",
    "testimonials",
    "twitter",
    "tweets",
    "social proof",
    "event",
    "conference",
    "userconf",
    "attendee feedback",
    "tweet cards",
    "light theme",
    "white background",
    "two column",
    "grid layout",
    "social media",
    "x twitter",
    "event testimonials",
    "conference feedback",
    "user quotes",
    "landing page",
    "marketing",
    "saas",
    "customer service",
    "community",
    "pink header",
    "cyan link",
    "italic title",
    "serif font",
    "follow button",
    "hashtag",
    "retweet",
    "favorite",
  ],
  fontFamily: ["Lora", "Inter"],
};
