export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-26.jpg",
  name: "landingfolio-hero-26",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "newsletter",
    "email subscription",
    "design inspiration",
    "UI inspiration",
    "weekly articles",
    "creative",
    "modern",
    "gradient background",
    "neon",
    "portrait",
    "artistic",
    "CTA",
    "call to action",
    "subscription form",
    "email list",
    "design resources",
    "SaaS",
    "marketing",
    "split layout",
    "two column",
    "checklist",
    "benefits list",
    "feature list",
    "ClarityUI",
    "landingfolio",
    "professional",
    "clean design",
    "light theme",
    "gradient button",
  ],
  fontFamily: ["Inter"],
};
