export const metadata = {
  imagePath: "agent-input/biography/free-pr-book.jpg",
  name: "free-pr-book",
  keywords: [
    "biography",
    "bio",
    "profile",
    "author",
    "authors",
    "meet the authors",
    "book",
    "ebook",
    "free book",
    "pr",
    "public relations",
    "media",
    "speaker",
    "startup",
    "entrepreneur",
    "advisor",
    "investor",
    "coo",
    "founder",
    "co-founder",
    "business",
    "marketing",
    "clarity",
    "call",
    "consultation",
    "two column",
    "grid layout",
    "card",
    "profile card",
    "social links",
    "twitter",
    "linkedin",
    "badge",
    "pill badge",
    "yellow badge",
    "white background",
    "light theme",
    "clean design",
    "minimal",
    "professional",
    "headshot",
    "portrait",
    "team",
    "about us",
    "landing page",
    "cameron herold",
    "adrian salamunovic",
  ],
  fontFamily: ["Inter"],
};
