export const metadata = {
  imagePath: "agent-input/contact-form/seedesign.jpg",
  name: "seedesign",
  keywords: [
    "contact form",
    "quote request",
    "get a quote",
    "design agency",
    "creative agency",
    "dark theme",
    "dark mode",
    "black background",
    "green accent",
    "form",
    "input fields",
    "dropdown",
    "textarea",
    "brief",
    "budget",
    "submit form",
    "lead generation",
    "landing page",
    "agency website",
    "design partner",
    "quality first",
    "quick turnaround",
    "flexible process",
    "3d decorations",
    "pixel art",
    "voxel",
    "geometric shapes",
    "founder",
    "book a call",
    "CTA",
    "call to action",
    "premium design",
    "success",
    "features list",
    "benefits",
    "testimonial",
    "avatar",
    "modern",
    "startup",
    "saas",
    "tech",
    "professional",
  ],
  fontFamily: ["Satoshi", "Inter"],
};
