export const metadata = {
  imagePath: "agent-input/testimonial-tweets/screen-studio.jpg",
  name: "screen-studio-testimonial",
  keywords: [
    "testimonial",
    "testimonials",
    "tweets",
    "twitter",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "dark theme",
    "black background",
    "masonry layout",
    "two column",
    "tweet cards",
    "social media",
    "screen studio",
    "screen recording",
    "video production",
    "pie6k",
    "adam",
    "developer testimonials",
    "product testimonials",
    "saas testimonials",
    "user quotes",
    "twitter style",
    "tweet wall",
    "love wall",
    "customer love",
    "wall of love",
    "mentions",
    "handles",
    "avatars",
    "meet users",
  ],
  fontFamily: ["Inter"],
};
