export const metadata = {
  imagePath: "agent-input/biography/figma-academy.jpg",
  name: "figma-academy",
  keywords: [
    "biography",
    "bio",
    "creator",
    "meet the creator",
    "profile",
    "profile card",
    "about me",
    "about section",
    "personal",
    "introduction",
    "designer profile",
    "twitter",
    "social proof",
    "trusted by",
    "tooltip",
    "speech bubble",
    "name badge",
    "avatar",
    "profile image",
    "dark background",
    "diagonal",
    "gradient card",
    "glassmorphism",
    "light card",
    "purple gradient",
    "lavender",
    "figma",
    "design course",
    "cohort",
    "maven",
    "shift nudge",
    "UI design",
    "mentor",
    "advisor",
    "founding designer",
    "product designer",
    "landing page",
    "hero section",
    "personal branding",
    "navy blue",
    "modern",
    "clean",
    "minimal",
  ],
  fontFamily: ["Inter"],
};
