export const metadata = {
  imagePath: "agent-input/before-after/uplift-founders.jpg",
  name: "uplift-founders",
  keywords: [
    "before after",
    "comparison",
    "toggle",
    "switch",
    "founder",
    "startup",
    "coaching",
    "leadership",
    "empowerment",
    "scale",
    "growth",
    "decision making",
    "emotional stability",
    "relationships",
    "team",
    "hero section",
    "landing page",
    "cream background",
    "beige",
    "dark card",
    "contrast",
    "italic headline",
    "bold typography",
    "two column",
    "split layout",
    "feature card",
    "shaky founders",
    "uplift",
    "transformation",
    "mindset",
    "entrepreneur",
  ],
  fontFamily: ["Inter"],
};
