export const metadata = {
  imagePath: "agent-input/contact-form/graffio.jpg",
  name: "graffio-contact-form",
  keywords: [
    "contact",
    "contact form",
    "form",
    "get in touch",
    "let's talk",
    "dark theme",
    "dark mode",
    "minimal",
    "minimalist",
    "modern",
    "email",
    "phone",
    "message",
    "textarea",
    "input fields",
    "send button",
    "two column",
    "split layout",
    "agency",
    "studio",
    "portfolio",
    "freelancer",
    "creative",
    "instagram",
    "linkedin",
    "social links",
    "graffio",
    "hola",
    "collaborative",
    "projects",
    "enquiries",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
