export const metadata = {
  imagePath: "agent-input/testimonial-tweets/superwhisper.jpg",
  name: "superwhisper-testimonial",
  keywords: [
    "testimonial",
    "testimonials",
    "tweets",
    "twitter",
    "x",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "dark theme",
    "dark mode",
    "black background",
    "card grid",
    "masonry",
    "bento",
    "avatar",
    "profile",
    "handle",
    "username",
    "mention",
    "superwhisper",
    "whisper",
    "dictation",
    "voice typing",
    "speech to text",
    "transcription",
    "ai",
    "mac app",
    "productivity",
    "video thumbnail",
    "media card",
    "pill badge",
    "reviews badge",
    "social media",
    "endorsement",
    "recommendation",
  ],
  fontFamily: ["Inter"],
};
