export const metadata = {
  imagePath: "agent-input/before-after/practical-ui.jpg",
  name: "practical-ui-before-after",
  keywords: [
    "before after",
    "comparison",
    "before and after",
    "property features",
    "real estate",
    "airbnb",
    "listing",
    "ui comparison",
    "ux improvement",
    "readability",
    "content structure",
    "text formatting",
    "wall of text",
    "structured content",
    "icon list",
    "feature list",
    "card design",
    "white card",
    "light theme",
    "two column",
    "side by side",
    "good vs bad",
    "do and dont",
    "best practice",
    "clean design",
    "minimal",
    "saas",
    "landing page",
    "ux tips",
    "practical ui",
    "waterfront",
    "check-in experience",
    "parking",
    "amenities",
  ],
  fontFamily: ["Inter"],
};
