export const metadata = {
  imagePath: "agent-input/biography/lovro-podobnik.jpg",
  name: "lovro-podobnik",
  keywords: [
    "biography",
    "bio",
    "profile",
    "about",
    "about me",
    "designer",
    "freelance",
    "freelancer",
    "personal",
    "introduction",
    "portfolio",
    "dark theme",
    "dark mode",
    "glow effect",
    "cyan glow",
    "teal",
    "profile card",
    "profile image",
    "portrait",
    "quote",
    "highlighted quote",
    "blockquote",
    "two column",
    "split layout",
    "services",
    "pricing",
    "flat rate",
    "monthly rate",
    "subscription",
    "design services",
    "creative",
    "professional",
    "personal branding",
    "landing page",
    "hero section",
    "about section",
    "glass effect",
    "glassmorphism",
    "behind the screen",
    "background text",
    "watermark text",
    "lovro",
    "podobnik",
  ],
  fontFamily: ["Inter"],
};
