export const metadata = {
  imagePath: "agent-input/contact-form/espanium.jpg",
  name: "espanium",
  keywords: [
    "contact form",
    "contact",
    "form",
    "consultation",
    "request form",
    "lead generation",
    "lead form",
    "immigration",
    "residence permit",
    "visa",
    "spain",
    "spanish",
    "legal services",
    "consultation request",
    "free consultation",
    "input fields",
    "text input",
    "textarea",
    "submit button",
    "send request",
    "team",
    "team members",
    "consultant",
    "professional",
    "two column layout",
    "split layout",
    "light theme",
    "gray background",
    "minimal",
    "clean design",
    "professional services",
    "law firm",
    "immigration services",
    "relocation",
    "expat services",
    "permit application",
    "avatar",
    "profile picture",
    "circular avatar",
    "blue accent",
    "outlined button",
    "privacy policy",
    "data processing",
    "gdpr",
    "landing page",
    "hero section",
    "cta section",
  ],
  fontFamily: ["Inter"],
};
