export const metadata = {
  imagePath: "agent-input/contact-form/xizt-agency.jpg",
  name: "xizt-agency",
  keywords: [
    "contact form",
    "contact us",
    "consultation form",
    "inquiry form",
    "lead capture",
    "project inquiry",
    "agency",
    "creative agency",
    "design agency",
    "consulting",
    "consultation request",
    "budget selector",
    "price range",
    "project budget",
    "inline form",
    "conversational form",
    "sentence form",
    "natural language form",
    "white background",
    "light theme",
    "minimal design",
    "clean design",
    "modern form",
    "budget chips",
    "budget pills",
    "underline input",
    "inline input",
    "send request",
    "Hey We are ready",
    "consult you",
    "xizt",
    "service inquiry",
    "project details",
    "email capture",
  ],
  fontFamily: ["Inter"],
};
