export const metadata = {
  imagePath: "agent-input/biography/liftoff-course-2021.jpg",
  name: "liftoff-course-2021",
  keywords: [
    "biography",
    "bio",
    "author",
    "course author",
    "about",
    "about me",
    "about the author",
    "profile",
    "personal",
    "instructor",
    "two column",
    "split layout",
    "duotone",
    "pink duotone",
    "magenta",
    "photo with text",
    "signature",
    "handwritten signature",
    "social icons",
    "twitter",
    "instagram",
    "dribbble",
    "product designer",
    "software engineer",
    "developer",
    "Wisconsin",
    "Array Themes",
    "Atomic Blocks",
    "Mike McAlister",
    "light theme",
    "white card",
    "gray background",
    "professional bio",
    "personal branding",
    "course landing page",
    "liftoff course",
    "recurring revenue",
    "digital products",
    "SaaS",
    "product builder",
    "maker",
  ],
  fontFamily: ["Inter"],
};
