export const metadata = {
  imagePath: "agent-input/testimonial-slider/parable.jpg",
  name: "parable-testimonial-slider",
  keywords: [
    "testimonial",
    "testimonials",
    "slider",
    "carousel",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "quotes",
    "quote card",
    "quotation marks",
    "light theme",
    "lavender background",
    "purple accent",
    "minimal",
    "minimalist",
    "clean design",
    "centered layout",
    "navigation arrows",
    "square buttons",
    "parable",
    "prisms",
    "landing page",
    "saas",
    "startup",
    "education",
    "consumer tech",
  ],
  fontFamily: ["Inter"],
};
