export const metadata = {
  imagePath: "agent-input/feature-carousel/people-app.jpg",
  name: "people-crm-showcase",
  keywords: [
    "crm",
    "people",
    "customer relationship management",
    "contacts",
    "leads",
    "sales",
    "recruitment",
    "fundraising",
    "support",
    "saas",
    "dashboard",
    "app showcase",
    "feature showcase",
    "desktop app",
    "macos window",
    "table view",
    "data table",
    "contact list",
    "email management",
    "project management",
    "budget tracking",
    "team collaboration",
    "enterprise",
    "business software",
    "landing page hero",
    "product demo",
    "app preview",
    "gradient background",
    "modern ui",
    "clean design",
    "tabs navigation",
    "sidebar navigation",
    "traffic lights",
    "mac window",
    "software interface",
  ],
  fontFamily: ["Inter"],
};
