export const metadata = {
  imagePath: "agent-input/biography/show-them-course.jpg",
  name: "show-them-course",
  keywords: [
    "biography",
    "bio",
    "instructor",
    "course instructor",
    "about",
    "about me",
    "credentials",
    "portfolio",
    "landing page",
    "consultant",
    "speaker",
    "conference speaker",
    "author",
    "book author",
    "workshop host",
    "maker",
    "product builder",
    "content creator",
    "educator",
    "dark theme",
    "charcoal background",
    "grid layout",
    "two column",
    "card grid",
    "numbered list",
    "course outline",
    "Rob Hope",
    "One Page Love",
    "Landing Page Hot Tips",
    "Unsplash",
    "Webflow Conf",
    "WordCamp",
    "professional bio",
    "personal branding",
    "social proof",
    "expertise showcase",
    "serif heading",
    "italic heading",
    "playfair display",
  ],
  fontFamily: ["Inter", "Playfair Display"],
};
