export const metadata = {
  imagePath: "agent-input/biography/margherita-fortuna.jpg",
  name: "margherita-fortuna",
  keywords: [
    "biography",
    "bio",
    "profile",
    "personal",
    "about me",
    "about",
    "portfolio",
    "designer",
    "freelancer",
    "creative",
    "dark theme",
    "dark green",
    "olive green",
    "forest green",
    "elegant",
    "serif font",
    "instrument serif",
    "italic",
    "awards",
    "achievements",
    "FWA",
    "Awwwards",
    "CSSDA",
    "web design awards",
    "jury member",
    "Rome",
    "Italy",
    "Italian",
    "art",
    "artistic",
    "warm tones",
    "gold accent",
    "rose accent",
    "dusty pink",
    "CTA button",
    "request portfolio",
    "contact",
    "profile image",
    "portrait",
    "flowers",
    "creative portrait",
    "single column",
    "vertical layout",
    "scrolling page",
    "long form",
    "storytelling",
    "personal website",
    "landing page",
    "introduction",
    "professional",
    "digital design",
    "web design",
    "UI designer",
    "UX designer",
    "brand designer",
    "attention to detail",
    "luxury",
    "sophisticated",
    "minimal",
    "clean design",
    "awards list",
    "credentials",
  ],
  fontFamily: ["Instrument Serif"],
};
