export const metadata = {
  imagePath: "agent-input/biography/endless.jpg",
  name: "endless",
  keywords: [
    "biography",
    "bio",
    "about",
    "about me",
    "about us",
    "profile",
    "founder",
    "founder bio",
    "team member",
    "personal profile",
    "portfolio",
    "introduction",
    "designer bio",
    "agency bio",
    "studio intro",
    "who we are",
    "solo founder",
    "freelancer",
    "design studio",
    "minimal",
    "clean",
    "light theme",
    "white background",
    "simple layout",
    "text with avatar",
    "profile image",
    "circular avatar",
    "endless",
    "daryl ginn",
    "perth australia",
    "design agency",
    "tight-knit",
    "quality focused",
  ],
  fontFamily: ["Inter"],
};
