export const metadata = {
  imagePath: "agent-input/lead-capture-hero/pencil.jpg",
  name: "pencil-hero",
  keywords: [
    "hero section",
    "lead capture",
    "email signup",
    "waitlist",
    "request access",
    "design tool",
    "cursor",
    "IDE plugin",
    "developer tool",
    "ASCII art",
    "retro",
    "minimalist",
    "green theme",
    "sage green",
    "landing page",
    "SaaS",
    "product launch",
    "coming soon",
    "early access",
    "newsletter",
    "CTA form",
    "backed by",
    "startup",
    "design mode",
    "code editor",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
