export const metadata = {
  imagePath: "agent-input/testimonial-tweets/alfread.jpg",
  name: "alfread-testimonial-tweets",
  keywords: [
    "testimonial",
    "twitter",
    "tweets",
    "social proof",
    "reviews",
    "customer feedback",
    "alfread",
    "scattered layout",
    "cards",
    "user quotes",
    "x",
    "social media",
    "light theme",
    "white background",
    "multi-card",
    "grid layout",
    "twitter cards",
    "tweet wall",
    "social testimonials",
    "verified badge",
    "user mentions",
    "read later app",
    "product hunt",
    "startup testimonials",
  ],
  fontFamily: ["Inter"],
};
