export const metadata = {
  imagePath: "agent-input/biography/made-by-porter.jpg",
  name: "made-by-porter",
  keywords: [
    "biography",
    "bio",
    "about",
    "about me",
    "about us",
    "profile",
    "founder",
    "founder bio",
    "team member",
    "personal profile",
    "portfolio",
    "introduction",
    "two column",
    "split layout",
    "photo with text",
    "author bio",
    "design engineer",
    "light theme",
    "minimal",
    "clean",
    "professional",
    "business bio",
    "company founder",
    "mission statement",
    "service description",
    "ecommerce",
    "tech consultant",
    "made by porter",
    "chris porter",
  ],
  fontFamily: ["Inter"],
};
