export const metadata = {
  imagePath: "agent-input/contact-form/summer-sprint.jpg",
  name: "summer-sprint",
  keywords: [
    "contact form",
    "lead capture",
    "signup form",
    "registration form",
    "sprint",
    "summer",
    "service inquiry",
    "business inquiry",
    "waitlist",
    "grab your spot",
    "starburst badge",
    "blue background",
    "pill inputs",
    "rounded form",
    "italic text",
    "marketing form",
    "service selection",
    "dropdown",
    "select",
    "first name",
    "last name",
    "email",
    "business name",
    "CTA",
    "call to action",
  ],
  fontFamily: ["Inter"],
};
