export const metadata = {
  imagePath: "agent-input/before-after/iphone-creator-course.jpg",
  name: "iphone-creator-course",
  keywords: [
    "before after",
    "comparison",
    "image slider",
    "before and after slider",
    "photo comparison",
    "lightroom preset",
    "preset pack",
    "photo editing",
    "photography",
    "iphone photography",
    "mobile photography",
    "course",
    "included resource",
    "bonus",
    "value proposition",
    "feature section",
    "two column",
    "side by side",
    "light theme",
    "white background",
    "badge",
    "pill badge",
    "pricing",
    "total value",
    "building photo",
    "architecture",
    "european building",
    "balcony",
    "slider control",
    "drag to compare",
    "interactive",
    "clean design",
    "minimal",
    "landing page",
    "course landing",
    "digital product",
    "creator",
    "content creator",
  ],
  fontFamily: ["Inter"],
};
