export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-32.jpg",
  name: "landingfolio-hero-32",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "book",
    "ebook",
    "lead capture",
    "email capture",
    "newsletter",
    "yellow background",
    "bright theme",
    "vibrant",
    "psychology of money",
    "finance",
    "financial literacy",
    "money management",
    "book promotion",
    "book landing",
    "free chapter",
    "download",
    "CTA",
    "call to action",
    "subscribe",
    "navigation",
    "header",
    "marketing",
    "conversion",
    "landingfolio",
    "rareblocks",
    "NFT",
    "artworks",
    "artists",
    "marketplace",
    "split layout",
    "two column",
    "form",
    "input field",
    "submit button",
    "lorem ipsum background",
    "text background",
    "serif font",
    "italic tagline",
    "underline text",
    "shopping cart",
    "login",
    "account",
  ],
  fontFamily: ["Inter"],
};
