export const metadata = {
  imagePath: "agent-input/testimonial-tweets/ilo.jpg",
  name: "ilo-testimonial",
  keywords: [
    "testimonial",
    "testimonials",
    "tweets",
    "twitter",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "light theme",
    "white background",
    "cream cards",
    "peach cards",
    "masonry layout",
    "two column",
    "tweet cards",
    "social media",
    "ilo",
    "twitter analytics",
    "analytics tool",
    "developer testimonials",
    "product testimonials",
    "saas testimonials",
    "user quotes",
    "twitter style",
    "tweet wall",
    "love wall",
    "customer love",
    "wall of love",
    "happy users",
    "mentions",
    "handles",
    "avatars",
    "warm colors",
    "soft design",
    "friendly design",
    "engagement metrics",
    "vanity metrics",
  ],
  fontFamily: ["Inter"],
};
