export const metadata = {
  imagePath: "agent-input/before-after/kyoso.jpg",
  name: "kyoso-before-after",
  keywords: [
    "before after",
    "comparison",
    "before and after",
    "platform comparison",
    "workflow comparison",
    "tool comparison",
    "hub and spoke",
    "centralized",
    "unified platform",
    "all in one",
    "workflow simplification",
    "tool consolidation",
    "ai creative",
    "marketing",
    "content creation",
    "brief",
    "image generation",
    "video generation",
    "animation",
    "upscale",
    "edit image",
    "light theme",
    "white background",
    "two column",
    "side by side",
    "concentric circles",
    "radial layout",
    "node diagram",
    "flow diagram",
    "connector lines",
    "dashed lines",
    "minimal",
    "clean design",
    "saas",
    "landing page",
    "feature section",
    "value proposition",
  ],
  fontFamily: ["Inter"],
};
