export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-28.jpg",
  name: "landingfolio-hero-28",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "delivery app",
    "delivery service",
    "mobile app",
    "dark theme",
    "dark mode",
    "gradient text",
    "gradient button",
    "purple gradient",
    "cyan gradient",
    "phone mockup",
    "smartphone",
    "app download",
    "SaaS",
    "startup",
    "logistics",
    "parcel delivery",
    "courier",
    "tracking",
    "notification card",
    "free trial",
    "CTA",
    "call to action",
    "navigation header",
    "DuskUI",
    "modern",
    "clean design",
    "split layout",
    "two column",
    "product showcase",
    "app promotion",
    "download now",
    "pricing",
    "subscription",
  ],
  fontFamily: ["Inter"],
};
