export const metadata = {
  imagePath: "agent-input/biography/portfolio-final-final.jpg",
  name: "portfolio-final-final",
  keywords: [
    "biography",
    "author",
    "portfolio",
    "landing page",
    "about me",
    "personal brand",
    "product designer",
    "ebook",
    "book",
    "guide",
    "testimonial",
    "letter",
    "introduction",
    "profile",
    "resume",
    "cv",
    "credentials",
    "awards",
    "press",
    "work experience",
    "clients",
    "two column layout",
    "sidebar",
    "card",
    "white theme",
    "clean design",
    "minimal",
    "professional",
    "corporate",
    "signature",
    "handwriting",
    "designer portfolio",
    "product design",
    "UX design",
    "career",
    "consulting",
  ],
  fontFamily: ["Inter", "Caveat"],
};
