export const metadata = {
  imagePath: "agent-input/lead-capture-hero/fundamentals-uiux.jpg",
  name: "uiux-book-hero",
  keywords: [
    "hero",
    "lead capture",
    "email capture",
    "newsletter",
    "landing page",
    "ebook",
    "book",
    "guide",
    "UI/UX",
    "user interface",
    "user experience",
    "design",
    "web design",
    "free preview",
    "download",
    "cta",
    "call to action",
    "subscribe",
    "dark theme",
    "navy theme",
    "elegant",
    "premium",
    "vintage",
    "gold",
    "illustration",
    "education",
    "learning",
    "course",
    "design book",
    "design guide",
    "creative",
  ],
  fontFamily: ["Playfair Display", "Inter"],
};
