export const metadata = {
  imagePath: "agent-input/feature-carousel/fontface-dojo.jpg",
  name: "font-preview-carousel",
  keywords: [
    "font preview",
    "font showcase",
    "font carousel",
    "typography",
    "font comparison",
    "font grid",
    "font gallery",
    "popular fonts",
    "font selector",
    "pangram",
    "quick brown fox",
    "font face",
    "font display",
    "typeface preview",
    "serif fonts",
    "sans-serif fonts",
    "italic fonts",
    "font browser",
    "font library",
    "web fonts",
    "google fonts",
    "font collection",
    "font tester",
    "font sampler",
  ],
  fontFamily: [
    "Inter",
    "Playfair Display",
    "DM Serif Display",
    "Urbanist",
    "Source Code Pro",
    "Lora",
    "Roboto Slab",
  ],
};
