export const metadata = {
  imagePath: "agent-input/before-after/viewport-v2.jpg",
  name: "viewport-before-after",
  keywords: [
    "before after",
    "comparison",
    "before and after",
    "file organization",
    "chaotic files",
    "organized files",
    "figma",
    "design files",
    "content library",
    "brand assets",
    "archive",
    "inspiration",
    "process book",
    "project management",
    "file management",
    "design workflow",
    "productivity",
    "save time",
    "efficiency",
    "early access",
    "cta button",
    "hero section",
    "feature showcase",
    "saas landing",
    "product demo",
    "screenshot comparison",
    "overlay layout",
    "stacked images",
    "light theme",
    "white background",
    "mint green button",
    "purple accent",
    "indigo label",
    "clean design",
    "minimal",
    "viewport",
    "highlights",
    "capture",
    "share",
  ],
  fontFamily: ["Inter"],
};
