export const metadata = {
  imagePath: "agent-input/contact-form/innovation-initiative.jpg",
  name: "innovation-initiative",
  keywords: [
    "contact form",
    "contact",
    "form",
    "lead capture",
    "lead generation",
    "newsletter",
    "signup",
    "registration",
    "innovation",
    "initiative",
    "enterprise",
    "dark theme",
    "dark mode",
    "gradient background",
    "purple gradient",
    "abstract background",
    "wave pattern",
    "curved lines",
    "connect",
    "organization",
    "business",
    "B2B",
    "SaaS",
    "tech",
    "technology",
    "modern",
    "minimal",
    "clean design",
    "lime green button",
    "green accent",
    "two column layout",
    "split layout",
    "footer",
    "privacy policy",
    "copyright",
  ],
  fontFamily: ["Inter"],
};
