export const metadata = {
  imagePath: "agent-input/feature-carousel/pfpid.jpg",
  name: "rarity-feature-card",
  keywords: [
    "rarity",
    "nft",
    "pfp",
    "profile picture",
    "collectible",
    "variant",
    "color selector",
    "feature card",
    "showcase",
    "limited edition",
    "exclusive",
    "geometric pattern",
    "sacred geometry",
    "luxury",
    "premium",
    "mint",
    "blockchain",
    "digital collectible",
    "hero section",
    "product showcase",
  ],
  fontFamily: ["Playfair Display"],
};
