export const metadata = {
  imagePath: "agent-input/dribble-hero/dreamflux-ai.png",
  name: "dreamflux-ai-hero",
  keywords: [
    "hero",
    "ai",
    "artificial intelligence",
    "image generation",
    "text to image",
    "landing page",
    "light theme",
    "white background",
    "image grid",
    "gallery",
    "creative",
    "design tool",
    "saas",
    "startup",
    "cta",
    "call to action",
    "navigation",
    "header",
    "social proof",
    "user avatars",
    "modern",
    "minimal",
    "clean",
    "dreamflux",
    "visuals",
    "stunning",
    "breathtaking",
    "high quality",
    "two column",
    "split layout",
  ],
  fontFamily: ["Inter"],
};
