export const metadata = {
  imagePath: "agent-input/biography/pyrismic.jpg",
  name: "pyrismic",
  keywords: [
    "biography",
    "bio",
    "profile",
    "founder",
    "freelancer",
    "about me",
    "personal story",
    "entrepreneur",
    "startup founder",
    "mint background",
    "cyan background",
    "pastel",
    "light theme",
    "italic heading",
    "serif heading",
    "circular photo",
    "profile picture",
    "signature",
    "handwritten signature",
    "star decoration",
    "decorative stars",
    "testimonial",
    "about section",
    "landing page",
    "personal website",
    "portfolio",
    "introduction",
    "brand story",
    "company founder",
    "jamie syke",
    "pyrismic",
    "bumble",
    "universal music",
    "porsche",
    "ava",
    "brotherhood",
    "product design",
    "design solutions",
    "freelance platform",
    "saas",
    "elegant",
    "clean design",
    "centered layout",
    "narrow content",
  ],
  fontFamily: ["Playfair Display", "Inter"],
};
