export const metadata = {
  imagePath: "agent-input/feature-carousel/kyoso.jpg",
  name: "creative-partner-showcase",
  keywords: [
    "creative partner",
    "agentic creativity",
    "AI creative",
    "content generation",
    "social media",
    "advertising",
    "multi-platform",
    "campaign",
    "product showcase",
    "chat interface",
    "AI assistant",
    "marketing",
    "brand content",
    "carousel",
    "feature showcase",
    "platform cards",
    "hero section",
    "SaaS landing",
    "AI tool",
    "content creator",
  ],
  fontFamily: ["Inter"],
};
