export const metadata = {
  imagePath: "/Users/choesumin/Desktop/dev/choisumin/landing-mon-components/agent-input/landingfolio-stats/stats-19.jpg",
  name: "stats-19",
  keywords: [
    "stats",
    "statistics",
    "metrics",
    "dark theme",
    "black background",
    "serif italic",
    "instrument serif",
    "card container",
    "border",
    "four columns",
    "students",
    "teachers",
    "countries",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
