export const metadata = {
  imagePath: "/Users/choesumin/Desktop/dev/choisumin/landing-mon-components/agent-input/landingfolio-stats/stats-18.jpg",
  name: "stats-18",
  keywords: [
    "stats",
    "statistics",
    "metrics",
    "dark theme",
    "blue glow",
    "numbers",
    "business stats",
    "revenue",
    "percentage",
    "pricing",
    "users",
    "read more link",
    "underline link",
    "dark background",
    "gradient glow",
  ],
  fontFamily: ["Inter"],
};
