export const metadata = {
  imagePath: "agent-input/testimonial-tweets/designer-daily-report.jpg",
  name: "designer-daily-report-testimonial",
  keywords: [
    "testimonial",
    "testimonials",
    "twitter",
    "tweets",
    "social proof",
    "reviews",
    "feedback",
    "customer reviews",
    "user feedback",
    "quotes",
    "light theme",
    "white background",
    "cards",
    "staggered layout",
    "twitter cards",
    "tweet embed",
    "designer daily report",
    "design inspiration",
    "chrome extension",
    "design tools",
    "curated content",
    "design resources",
    "bunny mascot",
    "playful illustration",
    "serif heading",
    "playfair display",
    "social media testimonials",
    "three column",
    "overlapping cards",
    "profile avatars",
    "hashtags",
    "checkmarks",
    "design community",
    "product hunt",
    "saas",
    "landing page",
    "inspiration section",
  ],
  fontFamily: ["Playfair Display", "Inter"],
};
