export const metadata = {
  imagePath: "agent-input/feature-carousel/comet.jpg",
  name: "comet-feature-showcase",
  keywords: [
    "feature",
    "showcase",
    "carousel",
    "tabs",
    "pill buttons",
    "browser mockup",
    "space theme",
    "dark card",
    "AI assistant",
    "comet",
    "product demo",
    "use cases",
    "category selector",
    "starry background",
    "planet",
    "cosmic",
    "actions",
    "eat",
    "browse",
    "email",
    "search",
    "talk",
    "shop",
    "watch",
    "travel",
  ],
  fontFamily: ["Inter"],
};
