export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-13.jpg",
  name: "landingfolio-hero-13",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "SaaS",
    "video conferencing",
    "video call",
    "video grid",
    "team collaboration",
    "remote work",
    "startup",
    "dark theme",
    "black background",
    "CTA",
    "call to action",
    "dual buttons",
    "primary button",
    "secondary button",
    "navigation",
    "header",
    "free trial",
    "talk to sales",
    "customer connection",
    "business growth",
    "targeting customers",
    "browser mockup",
    "gradient border",
    "pill buttons",
    "DuskUI",
    "landingfolio",
    "professional",
    "B2B",
    "B2C",
    "communication platform",
    "online meeting",
    "web conference",
    "participant grid",
    "serif headline",
    "elegant design",
  ],
  fontFamily: ["Inter"],
};
