export const metadata = {
  imagePath: "agent-input/biography/liftoff-course-2022.jpg",
  name: "liftoff-course-2022",
  keywords: [
    "biography",
    "bio",
    "about",
    "about me",
    "meet the creator",
    "instructor",
    "course instructor",
    "profile card",
    "introduction",
    "personal branding",
    "two column",
    "split layout",
    "photo bio",
    "gradient overlay",
    "purple gradient",
    "magenta",
    "pink purple",
    "white card",
    "social icons",
    "social links",
    "tiktok",
    "twitter",
    "dribbble",
    "instagram",
    "signature",
    "handwritten signature",
    "cursive signature",
    "product designer",
    "software engineer",
    "digital creator",
    "course creator",
    "liftoff",
    "mike mcalister",
    "array themes",
    "atomic blocks",
    "wisconsin",
    "serif heading",
    "playfair display",
    "caveat font",
    "rounded card",
    "modern bio",
    "creator economy",
    "digital products",
  ],
  fontFamily: ["Inter", "Playfair Display", "Caveat"],
};
