export const metadata = {
  imagePath: "agent-input/testimonial-tweets/zoommy.jpg",
  name: "zoommy-testimonial-tweets",
  keywords: [
    "testimonial",
    "twitter",
    "tweets",
    "social proof",
    "reviews",
    "customer feedback",
    "zoommy",
    "stock photos",
    "mac app",
    "free images",
    "masonry layout",
    "cards",
    "user quotes",
    "x",
    "social media",
    "purple",
    "gradient",
  ],
  fontFamily: ["Inter"],
};
