export const metadata = {
  imagePath: "agent-input/landingfolio-hero/hero-6.jpg",
  name: "landingfolio-hero-6",
  keywords: [
    "hero",
    "hero section",
    "landing page",
    "community",
    "developer resources",
    "resource sharing",
    "SaaS",
    "design components",
    "UI library",
    "developer tools",
    "floating cards",
    "testimonials",
    "social proof",
    "centered layout",
    "light theme",
    "clean design",
    "minimal",
    "modern",
    "call to action",
    "CTA",
    "navigation",
    "badge",
    "tag",
    "statistics",
    "resource count",
    "RAREBLOCKS",
    "Landingfolio",
  ],
  fontFamily: ["Inter"],
};
