export const metadata = {
  imagePath: "agent-input/contact-form/nvgt.jpg",
  name: "nvgt-contact-form",
  keywords: [
    "contact",
    "contact form",
    "form",
    "get in touch",
    "inquiry",
    "message",
    "name",
    "email",
    "startup",
    "growth",
    "fuel",
    "dark theme",
    "dark mode",
    "black background",
    "mint accent",
    "teal accent",
    "cyan accent",
    "italic headline",
    "serif font",
    "instrument serif",
    "two column",
    "split layout",
    "pill badge",
    "badge",
    "send button",
    "nvgt",
    "landing page",
    "saas",
    "agency",
    "business",
    "cta",
    "call to action",
    "input field",
    "textarea",
    "submit",
  ],
  fontFamily: ["Instrument Serif", "Inter"],
};
