export const metadata = {
  imagePath: "agent-input/feature-carousel/anytype.jpg",
  name: "desktop-app-dashboard",
  keywords: [
    "desktop app",
    "dashboard",
    "macos",
    "window",
    "app mockup",
    "anytype",
    "notion",
    "productivity",
    "categories",
    "grid",
    "cards",
    "tabs",
    "search",
    "profile",
    "contacts",
    "messages",
    "tasks",
    "files",
    "diary",
    "music",
    "videos",
    "bookmarks",
    "health",
    "finance",
    "personal dashboard",
    "workspace",
    "organization",
    "traffic lights",
    "mac window",
    "app ui",
    "software interface",
    "navigation tabs",
    "category cards",
  ],
  fontFamily: ["Inter"],
};
